apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cni-installer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dpf-operator
    app.kubernetes.io/part-of: dpf-operator
  {{- include "cni-installer.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.cniInstaller.serviceAccount.annotations | nindent 4 }}
