{{ include "validate" . }}
{{- if .Values.dpu.vpcOVNNode.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "vpc-ovn-node.fullname" . }}
  labels:
    {{- include "vpc-ovn-node.labels" . | nindent 4 }}
    {{- with .Values.serviceDaemonSet.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.serviceDaemonSet.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "vpc-ovn-node.selectorLabels" . | nindent 6 }}
  {{- with .Values.serviceDaemonSet.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "vpc-ovn-node.selectorLabels" . | nindent 8 }}
        {{- with .Values.serviceDaemonSet.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.serviceDaemonSet.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        # With this annotation we provide requests to the sidecar to fulfil.
        dpu.nvidia.com/ip-requests: |-
          {{- .Values.dpu.vpcOVNNode.ipRequests | toJson | nindent 10 }}
    spec:
      hostNetwork: true
      serviceAccountName: {{ include "vpc-ovn-node.serviceAccountName" . }}
      {{- with .Values.dpu.vpcOVNNode.imagePullSecrets | default .Values.imagePullSecrets}}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.dpu.vpcOVNNode.podSecurityContext | nindent 8 }}
      {{- with toYaml .Values.serviceDaemonSet.nodeSelector }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
              {{- . | nindent 12 }}
      {{- end }}
      {{- with .Values.dpu.vpcOVNNode.tolerations | default list }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: allocator
        image: {{ .Values.dpu.vpcOVNNode.initContainers.allocator.image.repository }}:{{ .Values.dpu.vpcOVNNode.initContainers.allocator.image.tag }}
        command: ["/ipallocator", "allocator"]
        imagePullPolicy: {{ .Values.dpu.vpcOVNNode.initContainers.allocator.image.pullPolicy }}
        restartPolicy: Always
        securityContext:
          # Needs to run as root to ensure that it can access the NVIPAM socket
          runAsUser: 0
        # We use preStop to deallocate the IP when the pod is deleted. Quoting the official docs:
        # PreStop is called immediately before a container is terminated due to an
        # API request or management event such as liveness/startup probe failure,
        # preemption, resource contention, etc. The handler is not called if the
        # container crashes or exits.
        lifecycle:
          preStop:
            exec:
              command: ["/ipallocator", "deallocator"]
        env:
        - name: IP_ALLOCATOR_REQUESTS
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['dpu.nvidia.com/ip-requests']
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /opt/cni/bin
          name: cni-bin-dir
          readOnly: true
        - mountPath: /var/lib/cni/nv-ipam
          name: nvipam-daemon-socket-dir
          readOnly: true
        - mountPath: /tmp/ips
          name: ips
        # Used for caching the result
        - mountPath: /var/lib/cni
          name: cache

      - name: vpc-ovn-dpu-provisioner
        image: {{ .Values.dpu.vpcOVNNode.initContainers.vpcOVNDpuProvisioner.image.repository }}:{{ .Values.dpu.vpcOVNNode.initContainers.vpcOVNDpuProvisioner.image.tag }}
        imagePullPolicy: {{ .Values.dpu.vpcOVNNode.initContainers.vpcOVNDpuProvisioner.image.pullPolicy }}
        volumeMounts:
        - name: host-openvswitch
          mountPath: /var/run/openvswitch
        - name: host-openvswitch-etc
          mountPath: /etc/openvswitch
        - mountPath: /tmp/ips
          name: ips
          readOnly: true
        securityContext:
          # Needs to run as root to ensure that it can access the OVS socket
          runAsUser: 0
          # Needs to be privileged to set device ip addresses (e.g. ovn-vtep bridge)
          privileged: true
        env:
        - name: OVN_SB_ENDPOINT
          value: {{ .Values.dpu.vpcOVNNode.initContainers.vpcOVNDpuProvisioner.env.ovnSbEndpoint | quote }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command: ["/vpc-ovn-dpu-provisioner"]

      containers:
        - name: vpc-ovn-node
          image: {{ .Values.dpu.vpcOVNNode.containers.vpcOVNNodeController.image.repository }}:{{ .Values.dpu.vpcOVNNode.containers.vpcOVNNodeController.image.tag }}
          command: ["/vpc-ovn-node"]
          imagePullPolicy: {{ .Values.dpu.vpcOVNNode.containers.vpcOVNNodeController.image.pullPolicy }}
          securityContext:
            {{ toYaml .Values.dpu.vpcOVNNode.containers.vpcOVNNodeController.securityContext | nindent 12 }}
          {{- with toYaml .Values.serviceDaemonSet.resources }}
          resources:
            limits:
              {{- . | nindent 14 }}
            requests:
              {{- . | nindent 14 }}
          {{- end }}
          volumeMounts:
          - name: host-openvswitch
            mountPath: /var/run/openvswitch
          - name: mellanox-etc
            mountPath: /etc/mellanox
            readOnly: true
          securityContext:
            # Needs to run as root to ensure that it can access the OVS socket
            runAsUser: 0
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName

        {{- if .Values.dpu.vpcOVNNode.containers.dhcpCNIDaemon.enabled }}
        - name: dhcp-cni-daemon
          image: {{ .Values.dpu.vpcOVNNode.containers.dhcpCNIDaemon.image.repository }}:{{ .Values.dpu.vpcOVNNode.containers.dhcpCNIDaemon.image.tag }}
          imagePullPolicy: {{ .Values.dpu.vpcOVNNode.containers.dhcpCNIDaemon.image.pullPolicy }}
          command: ["/opt/cni/bin/dhcp", "daemon"]
          volumeMounts:
          - name: dhcp-cni-bin-dir
            mountPath: /opt/cni/bin
          - name: netns
            mountPath: /var/run/netns
            mountPropagation: Bidirectional
          - name: dhcp-daemon-socket-dir
            mountPath: /run/cni
            mountPropagation: Bidirectional
          securityContext:
            runAsUser: 0
            privileged: true
        {{- end }}

      volumes:
      - name: host-openvswitch
        hostPath:
          path: {{ .Values.dpu.vpcOVNNode.volumes.hostOpenvswitch.path }}
          type: Directory
      - name: host-openvswitch-etc
        hostPath:
          path: {{ .Values.dpu.vpcOVNNode.volumes.hostOpenvswitchEtc.path }}
          type: Directory
      - name: ips
        emptyDir: {}
      - name: cni-bin-dir
        hostPath:
          path: {{ .Values.dpu.vpcOVNNode.volumes.cniBinDir.path }}
          type: Directory
      - name: cache
        emptyDir: {}
      - name: nvipam-daemon-socket-dir
        hostPath:
          path: {{ .Values.dpu.vpcOVNNode.volumes.nvipamDaemonSocketDir.path }}
          type: Directory
      - name: mellanox-etc
        hostPath:
          path: /etc/mellanox
          type: Directory
      - name: host-usr-lib
        hostPath:
          path: /usr/lib
      - name: host-usr-lib64
        hostPath:
          path: /usr/lib64
      - name: dhcp-cni-bin-dir
        hostPath:
          path: {{ .Values.dpu.vpcOVNNode.volumes.dhcpCNIBinDir.path }}
          type: Directory
      - name: dhcp-daemon-socket-dir
        hostPath:
          path: {{ .Values.dpu.vpcOVNNode.volumes.dhcpDaemonSocketDir.path }}
          type: DirectoryOrCreate
      - name: netns
        hostPath:
          path: /var/run/netns
          type: DirectoryOrCreate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vpc-ovn-node.roleName" . }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - serviceinterfaces
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - serviceinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - serviceinterfaces/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
  name: {{ include "vpc-ovn-node.roleBindingName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vpc-ovn-node.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "vpc-ovn-node.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
  name: {{ include "vpc-ovn-node.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
