imagePullSecrets: []

image:
  repository: quay.io/kata-containers/kata-deploy
  tag: 3.32.0@sha256:47c4cf29c9e8cf9bb7debab58761b672e1d4c93ee5e92db7b442ee00e7d561cc

nodeSelector: {}

containerd:
  # Override the host directory where containerd config lives.
  # When empty, defaults to /etc/containerd/.
  configDir: ""
  # Override the containerd config file name (for MLNX DPU nodes).
  configFileName: "config-mlnx.toml"

# Shim configuration. Each shim is explicitly enabled or disabled.
shims:
  qemu:
    enabled: true

# Default shim.
defaultShim: qemu


serviceAccount:
  annotations: {}
