# Adapted from https://github.com/spiffe/helm-charts-hardened/blob/aabc73b1e51976d6115fa1291b71889010ee64f9/charts/spire/charts/spiffe-csi-driver/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spiffe-csi-driver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spiffe-csi-driver.labels" . | nindent 4 }}
automountServiceAccountToken: false
