/*
Copyright 2026 NVIDIA

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by dpfdev generate-deprecation-warnings. DO NOT EDIT.

package controller

// These markers declare the RBAC the DeprecatedFieldsNotInUse scanner (reconcileDeprecatedFieldsUsage
// in deprecated_fields.go) needs: list+get on exactly the resources that currently have a
// deprecated field, grouped one marker per API group. They are generated from the same CRD scan as
// pkg/deprecation.KnownDeprecations, so they can never drift out of sync, and are deliberately
// independent of any other controller's RBAC markers.
// +kubebuilder:rbac:groups=operator.dpu.nvidia.com,resources=dpfoperatorconfigs,verbs=list;get
// +kubebuilder:rbac:groups=provisioning.dpu.nvidia.com,resources=dpudevices;dpunodes;dpus;dpusets,verbs=list;get
// +kubebuilder:rbac:groups=svc.dpu.nvidia.com,resources=dpudeployments;dpuservicechains;dpuserviceinterfaces;dpuserviceipams,verbs=list;get
