apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dms-role
  namespace: system
rules:
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - dpunodes
  verbs:
  - create
  - get
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - dpudevices
  verbs:
  - create
  - get
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - dpudevices/status
  verbs:
  - update
  - patch
  - get
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list