apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dpuagent-zerotrust-role
  namespace: system
rules:
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - dpus
  verbs:
  - get
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - dpus/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
