apiVersion: v1
kind: Secret
metadata:
  name: dpuagent-zerotrust-token
  namespace: system
  annotations:
    kubernetes.io/service-account.name: dpuagent-zerotrust
type: kubernetes.io/service-account-token
