ARG builder_image
ARG base_image
ARG rdma_cni_version=v1.6.0

# 1) dependency stage to create a dependency layer with go vendor folder and other dependencies
FROM --platform=${BUILDPLATFORM} ${builder_image} AS dependency
WORKDIR /workspace
ARG rdma_cni_version

# Copy source files needed for proper vendoring
COPY go.mod go.sum ./
COPY third_party/ third_party/
COPY api/ api/
COPY cmd/ cmd/
COPY test/ test/
COPY internal/ internal/
COPY pkg/ pkg/

# Vendor all dependencies with go build cache
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod vendor

# Copy the go source code so it can be distributed in the final image.
RUN mkdir -p src/dpf && \
    wget https://github.com/k8snetworkplumbingwg/rdma-cni/archive/refs/tags/${rdma_cni_version}.tar.gz -O src/rdma-cni-${rdma_cni_version}.tar.gz && \
    find . -name '*.go' -not -path "./hack/*" -not -path "./.gocache/*" \
    -exec cp --parents \{\}  src/dpf/ \; && \
    tar -czf source-code.tar.gz src

# 2) Builder stage builds go binaries (no emulation).
FROM --platform=${BUILDPLATFORM} ${builder_image} AS builder
WORKDIR /workspace

ARG gcflags
ARG ldflags
ARG TARGETARCH

ENV GO_LDFLAGS=${ldflags}
ENV GO_GCFLAGS=${gcflags}
ENV ARCH=${TARGETARCH}

# Copy the source code from the dependency image
COPY --from=dependency /workspace .

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=bind,source=Makefile,target=Makefile \
    --mount=type=bind,source=hack/tools/tools.mk,target=hack/tools/tools.mk \
    GOFLAGS="-mod=vendor" make binary-cni-installer

# 3) Declare images to copy binaries from. The reason we declare them here is so that we can parameterise the version.
FROM --platform=${TARGETPLATFORM} ghcr.io/k8snetworkplumbingwg/rdma-cni:${rdma_cni_version} AS rdmacni

# 4) Final stage copies artefacts from the builder and dependency stages.
FROM ${base_image}
ARG TARGETARCH

WORKDIR /

# Ensure all files are copied with the correct user.
ENV uid=65532
USER ${uid}:${uid}

# Add the source code.
COPY --chown=${uid} --from=dependency /workspace/source-code.tar.gz source-code.tar.gz

# Add the CNI Installer binary
COPY --chown=${uid} --from=builder /workspace/bin/ .

COPY --chown=${uid} --from=rdmacni /usr/bin/rdma /opt/cnis/rdma
