FROM nvcr.io/nvidia/doca/doca:3.0.0-full-rt-host

ARG TARGETARCH
ARG MFT_VERSION=4.29.0-131
ARG KUBECTL_VERSION=1.33.0
ARG PACKAGES="dpkg-dev=1.21.1ubuntu2.3 libusb-1.0-0=2:1.0.25-1ubuntu2 ipmitool=1.8.18-11ubuntu2.2 rshim curl=7.81.0-1ubuntu1.20 screen=4.9.0-1 pv=1.6.6-1build2 bridge-utils=1.7-1ubuntu3 iptables=1.8.7-1ubuntu5.2 iproute2=5.15.0-1ubuntu2"

# Enable deb-src to be able to fetch sources
RUN sed -i 's/^# deb-src/deb-src/g' /etc/apt/sources.list /etc/apt/sources.list.d/*

ARG ubuntu_mirror=http://archive.ubuntu.com/ubuntu/
RUN find /etc/apt/sources.list* -type f -exec sed -i \
      -e "s|http://archive.ubuntu.com/ubuntu/|${ubuntu_mirror}|g" \
      -e "s|http://ports.ubuntu.com/ubuntu/|${ubuntu_mirror}|g" \
      -e "s|http://security.ubuntu.com/ubuntu/|${ubuntu_mirror}|g" '{}' \;

RUN apt-get update && apt-get install -y -qq --no-install-recommends ${PACKAGES}

RUN case ${TARGETARCH} in \
        amd64) ARCH=x86_64 ;; \
        arm64) ARCH=arm64 ;; \
        *) echo "Unsupported architecture: ${TARGETARCH}" && exit 1 ;; \
    esac && \
    curl -fsSL https://www.mellanox.com/downloads/MFT/mft-${MFT_VERSION}-${ARCH}-deb.tgz | tar -xz -C /tmp && \
    cd /tmp/mft-${MFT_VERSION}-${ARCH}-deb && \
    ./install.sh --without-kernel

RUN mkdir -p /bfb-folder

WORKDIR /

RUN echo "ipmitool chassis power $reboot" > /usr/sbin/reboot && chmod +x /usr/sbin/reboot

RUN echo "echo 'running rshim'; rshim" > rshim.sh && chmod +x rshim.sh

RUN curl -LO https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /usr/local/bin

COPY ./internal/bf-slr/bf-slr.sh /usr/sbin
COPY ./internal/hostnetwork/hostnetwork.sh /opt/dpf/
COPY ./internal/dmsinit/dmsinit.sh /opt/dpf/

# Move source code to a directory
ARG PACKAGE_SOURCES
RUN test "${PACKAGE_SOURCES}" = "false" || ( \
      mkdir src && \
      cd src && \
      apt-get update && \
      apt-get source --download-only ${PACKAGES} && \
      curl -LO https://github.com/kubernetes/kubectl/archive/refs/tags/kubernetes-${KUBECTL_VERSION}.tar.gz && \
      cd / && \
      tar -cf source-code.tar src && \
      rm -rf src \
    )
