ARG builder_image
ARG ovs_cni_base_image

# 1) Dependency stage: create vendor/ inside the image (main module is vendor-on-build).
FROM --platform=${BUILDPLATFORM} ${builder_image} AS dependency
WORKDIR /workspace

COPY go.mod go.sum ./
# third_party/ is required by `go mod vendor`, other DPF internal packages
# import from third_party/forked/argoproj and nvidia-external-attacher.
COPY third_party/ third_party/
COPY api/ api/
COPY cmd/ cmd/
COPY test/ test/
COPY internal/ internal/
COPY pkg/ pkg/

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod vendor

# Copy the moved CNI source so it can be distributed in the final image.
RUN mkdir -p src && \
    find cmd/dpf-ovs-cni internal/cni/dpf-ovs-cni -name '*.go' \
    -exec cp --parents \{\}  src/ \; && \
    tar -czf source-code.tar.gz src

# 2) Build stage builds the OVS CNI binary.
FROM --platform=${BUILDPLATFORM} ${builder_image} AS builder
WORKDIR /workspace

COPY --from=dependency /workspace .

ARG goarch=
ARG TARGETARCH
ARG ldflags
ARG gcflags
ARG tag

ENV ARCH=${goarch:-$TARGETARCH}
ENV GO_LDFLAGS=${ldflags}
ENV GO_GCFLAGS=${gcflags}
ENV TAG=${tag}

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=bind,source=Makefile,target=Makefile \
    --mount=type=bind,source=hack/tools/tools.mk,target=hack/tools/tools.mk \
    GOFLAGS="-mod=vendor" make binary-ovs-cni

# 3) Final stage copies artifacts from the builder stage.
FROM ${ovs_cni_base_image}

ARG ubuntu_mirror=http://archive.ubuntu.com/ubuntu/
RUN find /etc/apt/sources.list* -type f -exec sed -i \
      -e "s|http://archive.ubuntu.com/ubuntu/|${ubuntu_mirror}|g" \
      -e "s|http://ports.ubuntu.com/ubuntu/|${ubuntu_mirror}|g" \
      -e "s|http://security.ubuntu.com/ubuntu/|${ubuntu_mirror}|g" '{}' \;

# Update packages from the base image.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get upgrade -y -qq

WORKDIR /

# Add the source code.
COPY --from=dependency /workspace/source-code.tar.gz source-code.tar.gz

# Add the OVS CNI binaries.
COPY --from=builder /workspace/bin/ovs /ovs
