ARG builder_image
ARG base_image

# 1) Build stage builds go binaries (no emulation).
FROM --platform=${BUILDPLATFORM} ${builder_image} AS builder
WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# Cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY ./ ./

# Ensure that no additional tools or artifacts are included.
RUN make clean

ARG gcflags
ARG ldflags
ARG storage_snap_csi_driver_go_ldflags
ARG TARGETARCH
ARG nvidia_external_attacher_go_ldflags

ENV STORAGE_SNAP_CSI_DRIVER_GO_LDFLAGS=\"${storage_snap_csi_driver_go_ldflags}\"
ENV GO_LDFLAGS=\"${ldflags}\"
ENV GO_GCFLAGS=\"${gcflags}\"
ENV ARCH=${TARGETARCH}
ENV NVIDIA_EXTERNAL_ATTACHER_GO_LDFLAGS=\"${nvidia_external_attacher_go_ldflags}\"

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    make binaries-storage-system

# Copy the go source code so it can be distributed in the final image.
RUN go mod vendor
RUN mkdir src && \
    find . -name '*.go' -not -path "./hack/*" -not -path "./.gocache/*" \
    -exec cp --parents \{\}  src/ \; && \
    tar -czf source-code.tar.gz src

# 2) Final stage copies artifacts from the builder stage.
FROM ${base_image}
ARG TARGETARCH

WORKDIR /

# Ensure all files are copied with the correct user.
ENV uid=65532
USER ${uid}:${uid}

# Add the source code.
COPY --chown=${uid} --from=builder /workspace/source-code.tar.gz source-code.tar.gz

# Add the DPF binaries
COPY --chown=${uid} --from=builder /workspace/bin/snap-csi-plugin /snap-csi-plugin
COPY --chown=${uid} --from=builder /workspace/bin/snap-node-driver /snap-node-driver
COPY --chown=${uid} --from=builder /workspace/bin/block-storage-vendor-dpu-plugin /block-storage-vendor-dpu-plugin
COPY --chown=${uid} --from=builder /workspace/bin/nfs-storage-vendor-dpu-plugin /nfs-storage-vendor-dpu-plugin
COPY --chown=${uid} --from=builder /workspace/bin/nvidia-external-attacher /nvidia-external-attacher
COPY --chown=${uid} --from=builder /workspace/bin/snap-host-controller /snap-host-controller
