ARG builder_image
ARG base_image

# 1) Builder stage builds go binaries (no emulation).
FROM --platform=${BUILDPLATFORM} ${builder_image} AS builder
WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# Cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY ./ ./

# Ensure that no additional tools or artifacts are included.
RUN make clean

ARG gcflags
ARG ldflags
ARG TARGETARCH
ARG TAG

ENV GO_LDFLAGS=\"${ldflags}\"
ENV GO_GCFLAGS=\"${gcflags}\"
ENV ARCH=${TARGETARCH}
# The TAG variable is necessary for the dpfctl versioning.
ENV TAG=${TAG}

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    make binaries-dpf-system

# Copy the go source code so it can be distributed in the final image.
RUN go mod vendor
RUN mkdir src && \
    find . -name '*.go' -not -path "./hack/*" -not -path "./.gocache/*" -exec cp --parents \{\}  src/ \; && \
    tar -czf source-code.tar.gz src

# 2) Final stage copies artefacts from the builder and dependency stages.
FROM ${base_image}
ARG TARGETARCH

WORKDIR /

# Ensure all files are copied with the correct user.
ENV uid=65532
USER ${uid}:${uid}

# Add the source code.
COPY --chown=${uid} --from=builder /workspace/source-code.tar.gz source-code.tar.gz

# Add the DPF system binaries
COPY --chown=${uid} --from=builder /workspace/bin/operator .
COPY --chown=${uid} --from=builder /workspace/bin/provisioning .
COPY --chown=${uid} --from=builder /workspace/bin/dpuservice .
COPY --chown=${uid} --from=builder /workspace/bin/servicechainset .
COPY --chown=${uid} --from=builder /workspace/bin/sfc-controller .
COPY --chown=${uid} --from=builder /workspace/bin/kamaji-cluster-manager .
COPY --chown=${uid} --from=builder /workspace/bin/static-cluster-manager .
COPY --chown=${uid} --from=builder /workspace/bin/ovshelper .
COPY --chown=${uid} --from=builder /workspace/bin/dpfctl .
COPY --chown=${uid} --from=builder /workspace/bin/dpu-detector .


