{
 "title": "DOCA Platform Framework - State",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dpu_status_conditions, namespace)"
    }
   },
   {
    "name": "dpu_conditions",
    "label": "DPU Conditions",
    "query": {
     "query": "label_values(dpu_status_conditions,type)"
    }
   },
   {
    "name": "dpuservice_conditions",
    "label": "DPUService Conditions",
    "query": {
     "query": "label_values(dpuservice_status_conditions,type)"
    }
   },
   {
    "name": "dpfoperatorconfig_conditions",
    "label": "DPFOperatorConfig Conditions",
    "query": {
     "query": "label_values(dpfoperatorconfig_status_conditions,type)"
    }
   },
   {
    "name": "dpuserviceinterface_conditions",
    "label": "DPUServiceInterface Conditions",
    "query": {
     "query": "label_values(dpuserviceinterface_status_conditions,type)"
    }
   },
   {
    "name": "dpuservicechain_conditions",
    "label": "DPUServiceChain Conditions",
    "query": {
     "query": "label_values(dpuservicechain_status_conditions,type)"
    }
   },
   {
    "name": "dpuserviceipam_conditions",
    "label": "DPUServiceIPAM Conditions",
    "query": {
     "query": "label_values(dpuserviceipam_status_conditions,type)"
    }
   },
   {
    "name": "dpudeployment_conditions",
    "label": "DPUDeployment Conditions",
    "query": {
     "query": "label_values(dpudeployment_status_conditions,type)"
    }
   },
   {
    "name": "dpucluster_conditions",
    "label": "DPUCluster Conditions",
    "query": {
     "query": "label_values(dpucluster_status_conditions,type)"
    }
   },
   {
    "name": "dpudevice_conditions",
    "label": "DPUDevice Conditions",
    "query": {
     "query": "label_values(dpudevice_status_conditions,type)"
    }
   },
   {
    "name": "dpuset_conditions",
    "label": "DPUSet Conditions",
    "query": {
     "query": "label_values(dpuset_status_conditions,type)"
    }
   },
   {
    "name": "dpunode_conditions",
    "label": "DPUNode Conditions",
    "query": {
     "query": "label_values(dpunode_status_conditions,type)"
    }
   },
   {
    "name": "dpunodemaintenance_conditions",
    "label": "DPUNodeMaintenance Conditions",
    "query": {
     "query": "label_values(dpunodemaintenance_status_conditions,type)"
    }
   },
   {
    "name": "dpuservicenad_conditions",
    "label": "DPUServiceNAD Conditions",
    "query": {
     "query": "label_values(dpuservicenad_status_conditions,type)"
    }
   },
   {
    "name": "dpustoragepolicy_conditions",
    "label": "DPUStoragePolicy Conditions",
    "query": {
     "query": "label_values(dpustoragepolicy_status_conditions,type)"
    }
   },
   {
    "name": "dpustoragevendor_conditions",
    "label": "DPUStorageVendor Conditions",
    "query": {
     "query": "label_values(dpustoragevendor_status_conditions,type)"
    }
   },
   {
    "name": "dpuvolume_conditions",
    "label": "DPUVolume Conditions",
    "query": {
     "query": "label_values(dpuvolume_status_conditions,type)"
    }
   },
   {
    "name": "dpuvolumeattachment_conditions",
    "label": "DPUVolumeAttachment Conditions",
    "query": {
     "query": "label_values(dpuvolumeattachment_status_conditions,type)"
    }
   },
   {
    "name": "dpuvirtualnetwork_conditions",
    "label": "DPUVirtualNetwork Conditions",
    "query": {
     "query": "label_values(dpuvirtualnetwork_status_conditions,type)"
    }
   },
   {
    "name": "dpuvpc_conditions",
    "label": "DPUVPC Conditions",
    "query": {
     "query": "label_values(dpuvpc_status_conditions,type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Provisioning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DPFOperatorConfig",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpfoperatorconfig_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpfoperatorconfig_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpfoperatorconfig_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUCluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpucluster_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpucluster_status_conditions{type=\"Created\"}) by (uid))",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpucluster_status_conditions{type=\"Created\"}) by (uid))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUDeployment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpudeployment_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpudeployment_status_conditions{type=\"Ready\"}) by (uid))",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpudeployment_status_conditions{type=\"Ready\"}) by (uid))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUDevice",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpudevice_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpudevice_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpudevice_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUNode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpunode_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpunode_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpunode_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUSet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuset_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuset_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuset_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpu_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpu_status_conditions{type=\"Ready\"}) by (uid)) or vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpu_status_conditions{type=\"Initialized\"}) by (uid))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUNodeMaintenance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpunodemaintenance_status_conditions{type=\"NodeEffectApplied\",status=\"True\"}) by (uid)) OR vector(0)",
     "legendFormat": "In Maintenance"
    },
    {
     "expr": "sum(max(dpunodemaintenance_status_conditions{type=\"NodeEffectApplied\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "DPUService",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuservice_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuservice_status_conditions{type=\"Ready\"}) by (uid))",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuservice_status_conditions{type=\"Ready\"}) by (uid))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUServiceChain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuservicechain_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuservicechain_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuservicechain_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUServiceInterface",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuserviceinterface_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuserviceinterface_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuserviceinterface_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUServiceIPAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuserviceipam_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuserviceipam_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuserviceipam_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUServiceNAD",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuservicenad_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuservicenad_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuservicenad_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUStoragePolicy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpustoragepolicy_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpustoragepolicy_status_conditions{type=\"Ready\"}) by (uid)) OR on() vector(-1)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpustoragepolicy_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUStorageVendor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpustoragevendor_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpustoragevendor_status_conditions{type=\"Ready\"}) by (uid)) OR on() vector(-1)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpustoragevendor_status_conditions{type=\"Ready\"}) by (uid)) OR on() vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUVolume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuvolume_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuvolume_status_conditions{type=\"Ready\"}) by (uid)) OR on() vector(-1)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuvolume_status_conditions{type=\"Ready\"}) by (uid)) OR on() vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUVolumeAttachment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuvolumeattachment_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuvolumeattachment_status_conditions{type=\"Ready\"}) by (uid)) OR on() vector(-1)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuvolumeattachment_status_conditions{type=\"Ready\"}) by (uid)) OR on() vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Networking & Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "IPPool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ippool_info) by (uid)) OR vector(0)"
    }
   ]
  },
  {
   "title": "ServiceChainSet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(servicechainset_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(servicechainset_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(servicechainset_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "ServiceChain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(servicechain_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(servicechain_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(servicechain_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "ServiceInterfaceSet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(serviceinterfaceset_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(serviceinterfaceset_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(serviceinterfaceset_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "ServiceInterface",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(serviceinterface_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(serviceinterface_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(serviceinterface_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "NetworkAttachmentDefinition",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(network_attachment_definition_info) by (uid)) OR vector(0)"
    }
   ]
  },
  {
   "title": "CIDRPool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(cidrpool_info) by (uid)) OR vector(0)"
    }
   ]
  },
  {
   "title": "DPUVPC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuvpc_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuvpc_status_conditions{type=\"Ready\"}) by (uid)) OR on() vector(-1)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuvpc_status_conditions{type=\"Ready\"}) by (uid)) OR on() vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUVirtualNetwork",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuvirtualnetwork_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuvirtualnetwork_status_conditions{type=\"Ready\"}) by (uid)) OR on() vector(-1)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuvirtualnetwork_status_conditions{type=\"Ready\"}) by (uid)) OR on() vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "DPUServices",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 20 },
   "targets": [
    { "expr": "dpuservice_info{}", "legendFormat": "Auto" },
    {
     "expr": "dpuservice_status_conditions{type=\"Ready\"} == 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  label_replace(\n    sum by(label_svc_dpu_nvidia_com_service) (\n      kube_daemonset_status_desired_number_scheduled\n        * on(daemonset, namespace) group_left(label_svc_dpu_nvidia_com_service)\n          kube_daemonset_labels{label_svc_dpu_nvidia_com_service!=\"\"}\n      or\n      kube_deployment_spec_replicas\n        * on(deployment, namespace) group_left(label_svc_dpu_nvidia_com_service)\n          kube_deployment_labels{label_svc_dpu_nvidia_com_service!=\"\"}\n    ),\n    \"service_id\", \"$1\", \"label_svc_dpu_nvidia_com_service\", \"(.*)\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DPUSets",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 20 },
   "targets": [
    { "expr": "dpuset_info{}", "legendFormat": "Auto" }
   ]
  },
  {
   "title": "DPUDeployments",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 20 },
   "targets": [
    { "expr": "dpudeployment_info{}", "legendFormat": "Auto" },
    {
     "expr": "dpudeployment_status_conditions{type=\"Ready\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}