---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpc-ovn-node-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - serviceinterfaces
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - serviceinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - serviceinterfaces/status
  verbs:
  - get
  - patch
  - update
