apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-bf3-p0-vfs
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/resourceName: nvidia.com/bf3-p0-vfs
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "name": "sriov-bf3-p0-vfs",
      "netAttachDefName": "default/sriov-bf3-p0-vfs",
      "resourceName": "nvidia.com/bf3-p0-vfs",
      "topology": "layer2",
      "type": "ovn-k8s-cni-overlay",
      "subnets": "192.168.100.0/24"
    }