- groupVersionKind:
    group: k8s.cni.cncf.io
    kind: NetworkAttachmentDefinition
    version: v1
  labelsFromPath:
    name:
      - metadata
      - name
    namespace:
      - metadata
      - namespace
    uid:
      - metadata
      - uid
  metricNamePrefix: network_attachment_definition
  metrics:
    - name: created
      help: Unix creation timestamp.
      each:
        gauge:
          path:
            - metadata
            - creationTimestamp
        type: Gauge
    - name: info
      help: Information about a NetworkAttachmentDefinition.
      each:
        type: Info
        info:
          labelsFromPath:
            name:
              - metadata
              - name