- groupVersionKind:
    group: svc.dpu.nvidia.com
    kind: ServiceInterface
    version: v1alpha1
  labelsFromPath:
    name:
      - metadata
      - name
    namespace:
      - metadata
      - namespace
    uid:
      - metadata
      - uid
  metricNamePrefix: dpf_serviceinterface
  metrics:
    - name: created
      help: Unix creation timestamp.
      each:
        gauge:
          path:
            - metadata
            - creationTimestamp
        type: Gauge
    - name: info
      help: Information about a ServiceInterface.
      each:
        type: Info
        info:
          labelsFromPath:
            name:
              - metadata
              - name
            interface_type:
              - spec
              - interfaceType
            node:
              - spec
              - node
    - name: status_conditions
      help: The condition of a ServiceInterface.
      each:
        stateSet:
          labelName: status
          labelsFromPath:
            type:
              - type
          list:
            - 'True'
            - 'False'
            - Unknown
          path:
            - status
            - conditions
          valueFrom:
            - status
        type: StateSet
    - name: status_condition_last_transition_time
      help: The condition last transition time of a ServiceInterface.
      each:
        gauge:
          nilIsZero: true
          labelsFromPath:
            type:
              - type
            status:
              - status
          path:
            - status
            - conditions
          valueFrom:
            - lastTransitionTime
        type: Gauge
