{{- if and .Values.deployHostManifests (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kube-state-metrics.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http-metrics
      interval: 30s
      scrapeTimeout: 10s
{{- end }}
