{{- if .Values.management.ovnCentral.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ovn-central.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "ovn-central.labels" . | nindent 4 }}
spec:
  replicas: {{ ternary 3 1 .Values.management.ovnCentral.enableHA }}
  serviceName: {{ include "ovn-central.fullname" . }}
  selector:
    matchLabels:
      app: ovn-central
      {{- include "ovn-central.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: ovn-central
        {{- include "ovn-central.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ovn-central.serviceAccountName" . }}
      affinity:
        {{- toYaml .Values.management.ovnCentral.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.management.ovnCentral.tolerations | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.management.ovnCentral.image.repository }}:{{ .Values.management.ovnCentral.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.management.ovnCentral.image.pullPolicy }}
        ports:
        - name: ovnnb
          containerPort: {{ .Values.management.ovnCentral.service.ovnnb.targetPort }}
        - name: ovnsb
          containerPort: {{ .Values.management.ovnCentral.service.ovnsb.targetPort }}
        command: {{ .Values.management.ovnCentral.command | default "['/ovn-central-run.sh']" }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.management.ovnCentral.enableHA }}
        - name: OVN_NB_DB
          value: "tcp:{{ include "ovn-central.fullname" . }}-0.{{ include "ovn-central.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.management.ovnCentral.service.ovnnb.targetPort }},tcp:{{ include "ovn-central.fullname" . }}-1.{{ include "ovn-central.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.management.ovnCentral.service.ovnnb.targetPort }},tcp:{{ include "ovn-central.fullname" . }}-2.{{ include "ovn-central.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.management.ovnCentral.service.ovnnb.targetPort }}"
        - name: OVN_SB_DB
          value: "tcp:{{ include "ovn-central.fullname" . }}-0.{{ include "ovn-central.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.management.ovnCentral.service.ovnsb.targetPort }},tcp:{{ include "ovn-central.fullname" . }}-1.{{ include "ovn-central.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.management.ovnCentral.service.ovnsb.targetPort }},tcp:{{ include "ovn-central.fullname" . }}-2.{{ include "ovn-central.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.management.ovnCentral.service.ovnsb.targetPort }}"
        {{- end }}
        - name: SERVICE_NAME
          value: {{ include "ovn-central.fullname" . }}
        - name: ENABLE_HA
          value: "{{ ternary "true" "false" .Values.management.ovnCentral.enableHA }}"
        - name: OVN_NB_PORT
          value: "{{ .Values.management.ovnCentral.service.ovnnb.targetPort }}"
        - name: OVN_SB_PORT
          value: "{{ .Values.management.ovnCentral.service.ovnsb.targetPort }}"
        volumeMounts:
        - mountPath: /var/lib/ovn
          name: host-lib-ovn
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - ovn-nbctl --timeout=5 show
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - ovn-nbctl --timeout=5 show
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
      {{- with .Values.management.ovnCentral.imagePullSecrets | default .Values.imagePullSecrets}}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: host-lib-ovn
        hostPath:
          path: {{ .Values.management.ovnCentral.hostOvnLibDir }}
          type: DirectoryOrCreate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ovn-central.roleName" . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
  name: {{ include "ovn-central.roleBindingName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ovn-central.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ovn-central.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
  name: {{ include "ovn-central.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
