apiVersion: v2
name: dpf-operator
description: DPF Operator manages the lifecycle of a DOCA Platform Framework system.
type: application
version: v0.1.0
appVersion: v0.1.0
annotations:
  dpfVersion: ""
  created: ""
  commit: ""
