arm64:
  nodeSelector:
    kubernetes.io/arch: arm64
    kubernetes.io/os: linux
  image:
    repository: example.com/ovs-cni-plugin
    tag: v0.1.0
  ovsCniPlugin:
    args:
    - |
      cp /ovs /host/opt/cni/bin/.ovs.tmp && \
      mv /host/opt/cni/bin/.ovs.tmp /host/opt/cni/bin/ovs && \
      exec sleep infinity
    containerSecurityContext:
      privileged: true
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 10m
        memory: 15Mi
imagePullSecrets: []
kubernetesClusterDomain: cluster.local

cniBinDir: /opt/cni/bin
