{{- if .Values.management.ovnCentral.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ovn-central.fullname" . }}
  labels:
    {{- include "ovn-central.labels" . | nindent 4 }}
    {{- with .Values.exposedPorts.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: NodePort
  selector:
    {{- include "ovn-central.selectorLabels" . | nindent 4 }}
  ports:
    {{- if (.Values.exposedPorts.ports).ovnnb }}
    - name: ovnnb
      protocol: {{ .Values.management.ovnCentral.service.ovnnb.protocol }}
      port: {{ .Values.management.ovnCentral.service.ovnnb.port }}
      targetPort: {{ .Values.management.ovnCentral.service.ovnnb.targetport }}
      {{- if .Values.management.ovnCentral.service.ovnnb.nodePort }}
      nodePort: {{ .Values.management.ovnCentral.service.ovnnb.nodePort }}
      {{- end }}
    {{- end }}
    {{- if (.Values.exposedPorts.ports).ovnsb }}
    - name: ovnsb
      protocol: {{ .Values.management.ovnCentral.service.ovnsb.protocol }}
      port: {{ .Values.management.ovnCentral.service.ovnsb.port }}
      targetPort: {{ .Values.management.ovnCentral.service.ovnsb.targetport }}
      {{- if .Values.management.ovnCentral.service.ovnsb.nodePort }}
      nodePort: {{ .Values.management.ovnCentral.service.ovnsb.nodePort }}
      {{- end }}
    {{- end }}
{{- end }}
