{{- if .Values.management.ovnCentral.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ovn-central.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "ovn-central.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.management.ovnCentral.replicaCount }}
  {{- with .Values.management.ovnCentral.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: ovn-central
      {{- include "ovn-central.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: ovn-central
        {{- include "ovn-central.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        {{- toYaml .Values.management.ovnCentral.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.management.ovnCentral.tolerations | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.management.ovnCentral.image.repository }}:{{ .Values.management.ovnCentral.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.management.ovnCentral.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.management.ovnCentral.service.ovnnb.port }}
        - containerPort: {{ .Values.management.ovnCentral.service.ovnsb.port }}
        command: {{ .Values.management.ovnCentral.command | default "['/bin/bash']" }}
        args: {{- toYaml .Values.management.ovnCentral.args | nindent 8 }}
        volumeMounts:
        - mountPath: /var/lib/ovn
          name: host-lib-ovn
        readinessProbe:
          exec:
            command: ["ovn-nbctl", "--timeout=5", "show"]
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          exec:
            command: ["ovn-nbctl", "--timeout=5", "show"]
          initialDelaySeconds: 30
          periodSeconds: 10
      {{- with .Values.management.ovnCentral.imagePullSecrets | default .Values.imagePullSecrets}}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: host-lib-ovn
        hostPath:
          path: {{ .Values.management.ovnCentral.hostOvnLibDir }}
          type: DirectoryOrCreate
{{- end }}
