---
apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUServiceConfiguration
metadata:
  name: snap-csi-plugin
  namespace: dpf-operator-system
spec:
  deploymentServiceName: snap-csi-plugin
  upgradePolicy:
    applyNodeEffect: false
  serviceConfiguration:
    deployInCluster: true
    helmChart:
      values:
        imagePullSecrets: $DPF_IMAGE_PULL_SECRET
        host:
          snapCsiPlugin:
            enabled: true
            emulationMode: "virtiofs"
            controller:
              plugin:
                image:
                  repository: $DPF_IMAGE_REGISTRY/storage-system
                  tag: $DPF_IMAGE_TAG
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                      - matchExpressions:
                          - key: "node-role.kubernetes.io/master"
                            operator: Exists
                      - matchExpressions:
                          - key: "node-role.kubernetes.io/control-plane"
                            operator: Exists
            node:
              plugin:
                image:
                  repository: $DPF_IMAGE_REGISTRY/storage-host
                  tag: $DPF_IMAGE_TAG
