serviceDaemonSet:
  labels: {}

image:
  repository: registry.k8s.io/node-problem-detector/node-problem-detector
  pullPolicy: IfNotPresent
  # Current tag is v1.35.1
  tag: v1.35.1@sha256:c380751accc5e15973f7bf98a3725c3c30826b36ae407903c34297be47b73bc6

imagePullSecrets: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
