serviceDaemonSet:
  labels: {}

image:
  repository: registry.k8s.io/node-problem-detector/node-problem-detector
  pullPolicy: IfNotPresent
  tag: v1.36.0@sha256:b4db5a168c5f6192c3fb3d650920d192d83776598fcdfcc092d16ca8dc9213ff

imagePullSecrets: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
