// /*
// Copyright 2026 NVIDIA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nvidia/doca-platform/pkg/openflow (interfaces: OpenFlowAPI)
//
// Generated by this command:
//
//	mockgen -copyright_file ../../hack/boilerplate.go.txt --build_flags=--mod=mod -package openflow -destination mock_flows.go . OpenFlowAPI
//

// Package openflow is a generated GoMock package.
package openflow

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOpenFlowAPI is a mock of OpenFlowAPI interface.
type MockOpenFlowAPI struct {
	ctrl     *gomock.Controller
	recorder *MockOpenFlowAPIMockRecorder
	isgomock struct{}
}

// MockOpenFlowAPIMockRecorder is the mock recorder for MockOpenFlowAPI.
type MockOpenFlowAPIMockRecorder struct {
	mock *MockOpenFlowAPI
}

// NewMockOpenFlowAPI creates a new mock instance.
func NewMockOpenFlowAPI(ctrl *gomock.Controller) *MockOpenFlowAPI {
	mock := &MockOpenFlowAPI{ctrl: ctrl}
	mock.recorder = &MockOpenFlowAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenFlowAPI) EXPECT() *MockOpenFlowAPIMockRecorder {
	return m.recorder
}

// AddFlows mocks base method.
func (m *MockOpenFlowAPI) AddFlows(ctx context.Context, flows, bridgeName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFlows", ctx, flows, bridgeName)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFlows indicates an expected call of AddFlows.
func (mr *MockOpenFlowAPIMockRecorder) AddFlows(ctx, flows, bridgeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFlows", reflect.TypeOf((*MockOpenFlowAPI)(nil).AddFlows), ctx, flows, bridgeName)
}

// AddMeter mocks base method.
func (m *MockOpenFlowAPI) AddMeter(ctx context.Context, meter, bridgeName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMeter", ctx, meter, bridgeName)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMeter indicates an expected call of AddMeter.
func (mr *MockOpenFlowAPIMockRecorder) AddMeter(ctx, meter, bridgeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMeter", reflect.TypeOf((*MockOpenFlowAPI)(nil).AddMeter), ctx, meter, bridgeName)
}
