---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
  labels:
    app.kubernetes.io/component: manager
spec:
  selector:
    matchLabels:
  replicas: 2
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/part-of: nodesriovdeviceplugin-controller
                  dpu.nvidia.com/component: nodesriovdeviceplugin-controller
      containers:
      - command:
        - /nodesriovdeviceplugin-controller
        - --leader-elect
        image: controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
