apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-problem-detector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-problem-detector.labels" . | nindent 4 }}
automountServiceAccountToken: true
