apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kata-containers.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kata-containers.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
