// /*
// Copyright 2025 NVIDIA.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nvidia/doca-platform/internal/sfccontroller/controllers (interfaces: ServiceChainAPI)
//
// Generated by this command:
//
//	mockgen -copyright_file ../../../hack/boilerplate.go.txt -package controller -destination mock_servicechain.go . ServiceChainAPI
//

// Package controller is a generated GoMock package.
package controller

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceChainAPI is a mock of ServiceChainAPI interface.
type MockServiceChainAPI struct {
	ctrl     *gomock.Controller
	recorder *MockServiceChainAPIMockRecorder
	isgomock struct{}
}

// MockServiceChainAPIMockRecorder is the mock recorder for MockServiceChainAPI.
type MockServiceChainAPIMockRecorder struct {
	mock *MockServiceChainAPI
}

// NewMockServiceChainAPI creates a new mock instance.
func NewMockServiceChainAPI(ctrl *gomock.Controller) *MockServiceChainAPI {
	mock := &MockServiceChainAPI{ctrl: ctrl}
	mock.recorder = &MockServiceChainAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceChainAPI) EXPECT() *MockServiceChainAPIMockRecorder {
	return m.recorder
}

// GenerateAndApplyOpenFlows mocks base method.
func (m *MockServiceChainAPI) GenerateAndApplyOpenFlows(ctx context.Context, ports [][]string, hashedName uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAndApplyOpenFlows", ctx, ports, hashedName)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateAndApplyOpenFlows indicates an expected call of GenerateAndApplyOpenFlows.
func (mr *MockServiceChainAPIMockRecorder) GenerateAndApplyOpenFlows(ctx, ports, hashedName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAndApplyOpenFlows", reflect.TypeOf((*MockServiceChainAPI)(nil).GenerateAndApplyOpenFlows), ctx, ports, hashedName)
}
