// /*
// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.
// */
//

// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab-master.nvidia.com/doca-platform-foundation/ovn-vpc/ovn/ovnlib (interfaces: OVNSBWrapper)
//
// Generated by this command:
//
//	mockgen -copyright_file ../../hack/boilerplate.go.txt -package mock -destination mock/OVNSBWrapper.go . OVNSBWrapper
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	cache "github.com/ovn-org/libovsdb/cache"
	client "github.com/ovn-org/libovsdb/client"
	model "github.com/ovn-org/libovsdb/model"
	ovsdb "github.com/ovn-org/libovsdb/ovsdb"
	sbdb "gitlab-master.nvidia.com/doca-platform-foundation/ovn-vpc/ovn/sbdb"
	gomock "go.uber.org/mock/gomock"
)

// MockOVNSBWrapper is a mock of OVNSBWrapper interface.
type MockOVNSBWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockOVNSBWrapperMockRecorder
	isgomock struct{}
}

// MockOVNSBWrapperMockRecorder is the mock recorder for MockOVNSBWrapper.
type MockOVNSBWrapperMockRecorder struct {
	mock *MockOVNSBWrapper
}

// NewMockOVNSBWrapper creates a new mock instance.
func NewMockOVNSBWrapper(ctrl *gomock.Controller) *MockOVNSBWrapper {
	mock := &MockOVNSBWrapper{ctrl: ctrl}
	mock.recorder = &MockOVNSBWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOVNSBWrapper) EXPECT() *MockOVNSBWrapperMockRecorder {
	return m.recorder
}

// Cache mocks base method.
func (m *MockOVNSBWrapper) Cache() *cache.TableCache {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cache")
	ret0, _ := ret[0].(*cache.TableCache)
	return ret0
}

// Cache indicates an expected call of Cache.
func (mr *MockOVNSBWrapperMockRecorder) Cache() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cache", reflect.TypeOf((*MockOVNSBWrapper)(nil).Cache))
}

// ClearAll mocks base method.
func (m *MockOVNSBWrapper) ClearAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearAll indicates an expected call of ClearAll.
func (mr *MockOVNSBWrapperMockRecorder) ClearAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAll", reflect.TypeOf((*MockOVNSBWrapper)(nil).ClearAll), ctx)
}

// Close mocks base method.
func (m *MockOVNSBWrapper) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockOVNSBWrapperMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockOVNSBWrapper)(nil).Close))
}

// Connect mocks base method.
func (m *MockOVNSBWrapper) Connect(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockOVNSBWrapperMockRecorder) Connect(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockOVNSBWrapper)(nil).Connect), arg0)
}

// Connected mocks base method.
func (m *MockOVNSBWrapper) Connected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Connected indicates an expected call of Connected.
func (mr *MockOVNSBWrapperMockRecorder) Connected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connected", reflect.TypeOf((*MockOVNSBWrapper)(nil).Connected))
}

// Create mocks base method.
func (m *MockOVNSBWrapper) Create(arg0 ...model.Model) ([]ovsdb.Operation, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].([]ovsdb.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOVNSBWrapperMockRecorder) Create(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOVNSBWrapper)(nil).Create), arg0...)
}

// CreateChassis mocks base method.
func (m *MockOVNSBWrapper) CreateChassis(ctx context.Context, encap *sbdb.Encap, params *sbdb.Chassis) (*sbdb.Chassis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChassis", ctx, encap, params)
	ret0, _ := ret[0].(*sbdb.Chassis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChassis indicates an expected call of CreateChassis.
func (mr *MockOVNSBWrapperMockRecorder) CreateChassis(ctx, encap, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChassis", reflect.TypeOf((*MockOVNSBWrapper)(nil).CreateChassis), ctx, encap, params)
}

// CurrentEndpoint mocks base method.
func (m *MockOVNSBWrapper) CurrentEndpoint() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentEndpoint")
	ret0, _ := ret[0].(string)
	return ret0
}

// CurrentEndpoint indicates an expected call of CurrentEndpoint.
func (mr *MockOVNSBWrapperMockRecorder) CurrentEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentEndpoint", reflect.TypeOf((*MockOVNSBWrapper)(nil).CurrentEndpoint))
}

// DeleteChassis mocks base method.
func (m *MockOVNSBWrapper) DeleteChassis(ctx context.Context, params *sbdb.ChassisDeleteParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChassis", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChassis indicates an expected call of DeleteChassis.
func (mr *MockOVNSBWrapperMockRecorder) DeleteChassis(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChassis", reflect.TypeOf((*MockOVNSBWrapper)(nil).DeleteChassis), ctx, params)
}

// Disconnect mocks base method.
func (m *MockOVNSBWrapper) Disconnect() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Disconnect")
}

// Disconnect indicates an expected call of Disconnect.
func (mr *MockOVNSBWrapperMockRecorder) Disconnect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnect", reflect.TypeOf((*MockOVNSBWrapper)(nil).Disconnect))
}

// DisconnectNotify mocks base method.
func (m *MockOVNSBWrapper) DisconnectNotify() chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisconnectNotify")
	ret0, _ := ret[0].(chan struct{})
	return ret0
}

// DisconnectNotify indicates an expected call of DisconnectNotify.
func (mr *MockOVNSBWrapperMockRecorder) DisconnectNotify() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisconnectNotify", reflect.TypeOf((*MockOVNSBWrapper)(nil).DisconnectNotify))
}

// Echo mocks base method.
func (m *MockOVNSBWrapper) Echo(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Echo", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Echo indicates an expected call of Echo.
func (mr *MockOVNSBWrapperMockRecorder) Echo(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Echo", reflect.TypeOf((*MockOVNSBWrapper)(nil).Echo), arg0)
}

// Get mocks base method.
func (m *MockOVNSBWrapper) Get(arg0 context.Context, arg1 model.Model) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockOVNSBWrapperMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOVNSBWrapper)(nil).Get), arg0, arg1)
}

// GetChassis mocks base method.
func (m *MockOVNSBWrapper) GetChassis(ctx context.Context, params *sbdb.ChassisGetParams) (*sbdb.Chassis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChassis", ctx, params)
	ret0, _ := ret[0].(*sbdb.Chassis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChassis indicates an expected call of GetChassis.
func (mr *MockOVNSBWrapperMockRecorder) GetChassis(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChassis", reflect.TypeOf((*MockOVNSBWrapper)(nil).GetChassis), ctx, params)
}

// GetEncap mocks base method.
func (m *MockOVNSBWrapper) GetEncap(ctx context.Context, params *sbdb.EncapGetParams) (*sbdb.Encap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncap", ctx, params)
	ret0, _ := ret[0].(*sbdb.Encap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncap indicates an expected call of GetEncap.
func (mr *MockOVNSBWrapperMockRecorder) GetEncap(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncap", reflect.TypeOf((*MockOVNSBWrapper)(nil).GetEncap), ctx, params)
}

// List mocks base method.
func (m *MockOVNSBWrapper) List(ctx context.Context, result any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockOVNSBWrapperMockRecorder) List(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOVNSBWrapper)(nil).List), ctx, result)
}

// ListChassis mocks base method.
func (m *MockOVNSBWrapper) ListChassis(ctx context.Context, params *sbdb.ChassisListParams) ([]*sbdb.Chassis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChassis", ctx, params)
	ret0, _ := ret[0].([]*sbdb.Chassis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChassis indicates an expected call of ListChassis.
func (mr *MockOVNSBWrapperMockRecorder) ListChassis(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChassis", reflect.TypeOf((*MockOVNSBWrapper)(nil).ListChassis), ctx, params)
}

// Monitor mocks base method.
func (m *MockOVNSBWrapper) Monitor(arg0 context.Context, arg1 *client.Monitor) (client.MonitorCookie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Monitor", arg0, arg1)
	ret0, _ := ret[0].(client.MonitorCookie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Monitor indicates an expected call of Monitor.
func (mr *MockOVNSBWrapperMockRecorder) Monitor(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Monitor", reflect.TypeOf((*MockOVNSBWrapper)(nil).Monitor), arg0, arg1)
}

// MonitorAll mocks base method.
func (m *MockOVNSBWrapper) MonitorAll(arg0 context.Context) (client.MonitorCookie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MonitorAll", arg0)
	ret0, _ := ret[0].(client.MonitorCookie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MonitorAll indicates an expected call of MonitorAll.
func (mr *MockOVNSBWrapperMockRecorder) MonitorAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MonitorAll", reflect.TypeOf((*MockOVNSBWrapper)(nil).MonitorAll), arg0)
}

// MonitorCancel mocks base method.
func (m *MockOVNSBWrapper) MonitorCancel(ctx context.Context, cookie client.MonitorCookie) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MonitorCancel", ctx, cookie)
	ret0, _ := ret[0].(error)
	return ret0
}

// MonitorCancel indicates an expected call of MonitorCancel.
func (mr *MockOVNSBWrapperMockRecorder) MonitorCancel(ctx, cookie any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MonitorCancel", reflect.TypeOf((*MockOVNSBWrapper)(nil).MonitorCancel), ctx, cookie)
}

// NewMonitor mocks base method.
func (m *MockOVNSBWrapper) NewMonitor(arg0 ...client.MonitorOption) *client.Monitor {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewMonitor", varargs...)
	ret0, _ := ret[0].(*client.Monitor)
	return ret0
}

// NewMonitor indicates an expected call of NewMonitor.
func (mr *MockOVNSBWrapperMockRecorder) NewMonitor(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMonitor", reflect.TypeOf((*MockOVNSBWrapper)(nil).NewMonitor), arg0...)
}

// Schema mocks base method.
func (m *MockOVNSBWrapper) Schema() ovsdb.DatabaseSchema {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Schema")
	ret0, _ := ret[0].(ovsdb.DatabaseSchema)
	return ret0
}

// Schema indicates an expected call of Schema.
func (mr *MockOVNSBWrapperMockRecorder) Schema() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schema", reflect.TypeOf((*MockOVNSBWrapper)(nil).Schema))
}

// SetOption mocks base method.
func (m *MockOVNSBWrapper) SetOption(arg0 client.Option) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOption", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOption indicates an expected call of SetOption.
func (mr *MockOVNSBWrapperMockRecorder) SetOption(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOption", reflect.TypeOf((*MockOVNSBWrapper)(nil).SetOption), arg0)
}

// Transact mocks base method.
func (m *MockOVNSBWrapper) Transact(arg0 context.Context, arg1 ...ovsdb.Operation) ([]ovsdb.OperationResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Transact", varargs...)
	ret0, _ := ret[0].([]ovsdb.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transact indicates an expected call of Transact.
func (mr *MockOVNSBWrapperMockRecorder) Transact(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transact", reflect.TypeOf((*MockOVNSBWrapper)(nil).Transact), varargs...)
}

// UpdateEndpoints mocks base method.
func (m *MockOVNSBWrapper) UpdateEndpoints(arg0 []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateEndpoints", arg0)
}

// UpdateEndpoints indicates an expected call of UpdateEndpoints.
func (mr *MockOVNSBWrapperMockRecorder) UpdateEndpoints(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEndpoints", reflect.TypeOf((*MockOVNSBWrapper)(nil).UpdateEndpoints), arg0)
}

// Where mocks base method.
func (m *MockOVNSBWrapper) Where(arg0 ...model.Model) client.ConditionalAPI {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Where", varargs...)
	ret0, _ := ret[0].(client.ConditionalAPI)
	return ret0
}

// Where indicates an expected call of Where.
func (mr *MockOVNSBWrapperMockRecorder) Where(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Where", reflect.TypeOf((*MockOVNSBWrapper)(nil).Where), arg0...)
}

// WhereAll mocks base method.
func (m *MockOVNSBWrapper) WhereAll(arg0 model.Model, arg1 ...model.Condition) client.ConditionalAPI {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WhereAll", varargs...)
	ret0, _ := ret[0].(client.ConditionalAPI)
	return ret0
}

// WhereAll indicates an expected call of WhereAll.
func (mr *MockOVNSBWrapperMockRecorder) WhereAll(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WhereAll", reflect.TypeOf((*MockOVNSBWrapper)(nil).WhereAll), varargs...)
}

// WhereAny mocks base method.
func (m *MockOVNSBWrapper) WhereAny(arg0 model.Model, arg1 ...model.Condition) client.ConditionalAPI {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WhereAny", varargs...)
	ret0, _ := ret[0].(client.ConditionalAPI)
	return ret0
}

// WhereAny indicates an expected call of WhereAny.
func (mr *MockOVNSBWrapperMockRecorder) WhereAny(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WhereAny", reflect.TypeOf((*MockOVNSBWrapper)(nil).WhereAny), varargs...)
}

// WhereCache mocks base method.
func (m *MockOVNSBWrapper) WhereCache(predicate any) client.ConditionalAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WhereCache", predicate)
	ret0, _ := ret[0].(client.ConditionalAPI)
	return ret0
}

// WhereCache indicates an expected call of WhereCache.
func (mr *MockOVNSBWrapperMockRecorder) WhereCache(predicate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WhereCache", reflect.TypeOf((*MockOVNSBWrapper)(nil).WhereCache), predicate)
}
