FROM nvcr.io/nvidia/doca/canonical:ubuntu24.04

ARG ubuntu_mirror=http://archive.ubuntu.com/ubuntu/
RUN find /etc/apt/sources.list* -type f -exec sed -i \
      -e "s|http://archive.ubuntu.com/ubuntu/|${ubuntu_mirror}|g" \
      -e "s|http://ports.ubuntu.com/ubuntu/|${ubuntu_mirror}|g" \
      -e "s|http://security.ubuntu.com/ubuntu/|${ubuntu_mirror}|g" '{}' \;

RUN dpkg -l | awk '/^ii/{print $2"="$3}' | sort > /initial-dpkg-list.txt

ARG PACKAGES="dpkg-dev ca-certificates ovn-central ovn-host ovn-common openvswitch-common"

RUN apt-get update && apt-get install -y -qq --no-install-recommends \
    ${PACKAGES} && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN dpkg -l | awk '/^ii/{print $2"="$3}' | sort > /after-dpkg-list.txt

# Create directory for sources
RUN mkdir -p /usr/src/packages

# Enable deb-src repositories in the new Ubuntu sources config
RUN sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources

# Download source for each main installed package
WORKDIR /usr/src/packages

ARG PACKAGE_SOURCES
RUN test "${PACKAGE_SOURCES}" = "false" || ( \
      apt-get update && \
      apt-get source --download-only ${PACKAGES} && \
      comm -23 /after-dpkg-list.txt /initial-dpkg-list.txt | xargs -r apt-get source --download-only && \
      rm -f /initial-dpkg-list.txt /after-dpkg-list.txt && \
      cd / && \
      tar -cf source-code.tar /usr/src/packages && \
      rm -rf /usr/src/packages && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/* \
    )

WORKDIR /

# Expose ovn-central northbound and southbound ports
EXPOSE 6641 6642

# Volume /etc/ovn volume can be used for ovn-central configuration.
# The rest needed for ovn-controller
VOLUME ["/etc/ovn", "/var/run/openvswitch", "/var/run/ovn", "/var/log/ovn"]
