// /*
// COPYRIGHT 2026 NVIDIA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nvidia/doca-platform/api/grpc/nvidia/storage/plugins/v1 (interfaces: IdentityServiceClient,StoragePluginServiceClient)
//
// Generated by this command:
//
//	mockgen -copyright_file ../../../../hack/boilerplate.go.txt -package mock -destination mock/Plugin.go github.com/nvidia/doca-platform/api/grpc/nvidia/storage/plugins/v1 IdentityServiceClient,StoragePluginServiceClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v1 "github.com/nvidia/doca-platform/api/grpc/nvidia/storage/plugins/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockIdentityServiceClient is a mock of IdentityServiceClient interface.
type MockIdentityServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityServiceClientMockRecorder
	isgomock struct{}
}

// MockIdentityServiceClientMockRecorder is the mock recorder for MockIdentityServiceClient.
type MockIdentityServiceClientMockRecorder struct {
	mock *MockIdentityServiceClient
}

// NewMockIdentityServiceClient creates a new mock instance.
func NewMockIdentityServiceClient(ctrl *gomock.Controller) *MockIdentityServiceClient {
	mock := &MockIdentityServiceClient{ctrl: ctrl}
	mock.recorder = &MockIdentityServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityServiceClient) EXPECT() *MockIdentityServiceClientMockRecorder {
	return m.recorder
}

// GetPluginInfo mocks base method.
func (m *MockIdentityServiceClient) GetPluginInfo(ctx context.Context, in *v1.GetPluginInfoRequest, opts ...grpc.CallOption) (*v1.GetPluginInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPluginInfo", varargs...)
	ret0, _ := ret[0].(*v1.GetPluginInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPluginInfo indicates an expected call of GetPluginInfo.
func (mr *MockIdentityServiceClientMockRecorder) GetPluginInfo(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPluginInfo", reflect.TypeOf((*MockIdentityServiceClient)(nil).GetPluginInfo), varargs...)
}

// Probe mocks base method.
func (m *MockIdentityServiceClient) Probe(ctx context.Context, in *v1.ProbeRequest, opts ...grpc.CallOption) (*v1.ProbeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Probe", varargs...)
	ret0, _ := ret[0].(*v1.ProbeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Probe indicates an expected call of Probe.
func (mr *MockIdentityServiceClientMockRecorder) Probe(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Probe", reflect.TypeOf((*MockIdentityServiceClient)(nil).Probe), varargs...)
}

// MockStoragePluginServiceClient is a mock of StoragePluginServiceClient interface.
type MockStoragePluginServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockStoragePluginServiceClientMockRecorder
	isgomock struct{}
}

// MockStoragePluginServiceClientMockRecorder is the mock recorder for MockStoragePluginServiceClient.
type MockStoragePluginServiceClientMockRecorder struct {
	mock *MockStoragePluginServiceClient
}

// NewMockStoragePluginServiceClient creates a new mock instance.
func NewMockStoragePluginServiceClient(ctrl *gomock.Controller) *MockStoragePluginServiceClient {
	mock := &MockStoragePluginServiceClient{ctrl: ctrl}
	mock.recorder = &MockStoragePluginServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoragePluginServiceClient) EXPECT() *MockStoragePluginServiceClientMockRecorder {
	return m.recorder
}

// CreateDevice mocks base method.
func (m *MockStoragePluginServiceClient) CreateDevice(ctx context.Context, in *v1.CreateDeviceRequest, opts ...grpc.CallOption) (*v1.CreateDeviceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDevice", varargs...)
	ret0, _ := ret[0].(*v1.CreateDeviceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDevice indicates an expected call of CreateDevice.
func (mr *MockStoragePluginServiceClientMockRecorder) CreateDevice(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDevice", reflect.TypeOf((*MockStoragePluginServiceClient)(nil).CreateDevice), varargs...)
}

// DeleteDevice mocks base method.
func (m *MockStoragePluginServiceClient) DeleteDevice(ctx context.Context, in *v1.DeleteDeviceRequest, opts ...grpc.CallOption) (*v1.DeleteDeviceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteDevice", varargs...)
	ret0, _ := ret[0].(*v1.DeleteDeviceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDevice indicates an expected call of DeleteDevice.
func (mr *MockStoragePluginServiceClientMockRecorder) DeleteDevice(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDevice", reflect.TypeOf((*MockStoragePluginServiceClient)(nil).DeleteDevice), varargs...)
}

// GetDevice mocks base method.
func (m *MockStoragePluginServiceClient) GetDevice(ctx context.Context, in *v1.GetDeviceRequest, opts ...grpc.CallOption) (*v1.GetDeviceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDevice", varargs...)
	ret0, _ := ret[0].(*v1.GetDeviceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevice indicates an expected call of GetDevice.
func (mr *MockStoragePluginServiceClientMockRecorder) GetDevice(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevice", reflect.TypeOf((*MockStoragePluginServiceClient)(nil).GetDevice), varargs...)
}

// GetSNAPProvider mocks base method.
func (m *MockStoragePluginServiceClient) GetSNAPProvider(ctx context.Context, in *v1.GetSNAPProviderRequest, opts ...grpc.CallOption) (*v1.GetSNAPProviderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSNAPProvider", varargs...)
	ret0, _ := ret[0].(*v1.GetSNAPProviderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSNAPProvider indicates an expected call of GetSNAPProvider.
func (mr *MockStoragePluginServiceClientMockRecorder) GetSNAPProvider(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSNAPProvider", reflect.TypeOf((*MockStoragePluginServiceClient)(nil).GetSNAPProvider), varargs...)
}

// ListDevices mocks base method.
func (m *MockStoragePluginServiceClient) ListDevices(ctx context.Context, in *v1.ListDevicesRequest, opts ...grpc.CallOption) (*v1.ListDevicesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDevices", varargs...)
	ret0, _ := ret[0].(*v1.ListDevicesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDevices indicates an expected call of ListDevices.
func (mr *MockStoragePluginServiceClientMockRecorder) ListDevices(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDevices", reflect.TypeOf((*MockStoragePluginServiceClient)(nil).ListDevices), varargs...)
}

// StoragePluginGetCapabilities mocks base method.
func (m *MockStoragePluginServiceClient) StoragePluginGetCapabilities(ctx context.Context, in *v1.StoragePluginGetCapabilitiesRequest, opts ...grpc.CallOption) (*v1.StoragePluginGetCapabilitiesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StoragePluginGetCapabilities", varargs...)
	ret0, _ := ret[0].(*v1.StoragePluginGetCapabilitiesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoragePluginGetCapabilities indicates an expected call of StoragePluginGetCapabilities.
func (mr *MockStoragePluginServiceClientMockRecorder) StoragePluginGetCapabilities(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoragePluginGetCapabilities", reflect.TypeOf((*MockStoragePluginServiceClient)(nil).StoragePluginGetCapabilities), varargs...)
}
