// /*
// Copyright 2026 NVIDIA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nvidia/doca-platform/internal/storage/snap/node-driver/snap-rpc (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -copyright_file ../../../../hack/boilerplate.go.txt -package mock -destination mock/SNAPClient.go github.com/nvidia/doca-platform/internal/storage/snap/node-driver/snap-rpc Client
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	v1alpha1 "github.com/nvidia/doca-platform/api/storage/v1alpha1"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// DestroyBlockDevice mocks base method.
func (m *MockClient) DestroyBlockDevice(nsid int, pciAddr string, hotplug bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyBlockDevice", nsid, pciAddr, hotplug)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyBlockDevice indicates an expected call of DestroyBlockDevice.
func (mr *MockClientMockRecorder) DestroyBlockDevice(nsid, pciAddr, hotplug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyBlockDevice", reflect.TypeOf((*MockClient)(nil).DestroyBlockDevice), nsid, pciAddr, hotplug)
}

// DestroyFSDevice mocks base method.
func (m *MockClient) DestroyFSDevice(deviceName, pciAddr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyFSDevice", deviceName, pciAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyFSDevice indicates an expected call of DestroyFSDevice.
func (mr *MockClientMockRecorder) DestroyFSDevice(deviceName, pciAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyFSDevice", reflect.TypeOf((*MockClient)(nil).DestroyFSDevice), deviceName, pciAddr)
}

// ExposeBlockDevice mocks base method.
func (m *MockClient) ExposeBlockDevice(dpuStatus v1alpha1.VolumeAttachmentStatusDPU, spec v1alpha1.VolumeAttachmentSpec, parameters map[string]string) (int, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExposeBlockDevice", dpuStatus, spec, parameters)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ExposeBlockDevice indicates an expected call of ExposeBlockDevice.
func (mr *MockClientMockRecorder) ExposeBlockDevice(dpuStatus, spec, parameters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExposeBlockDevice", reflect.TypeOf((*MockClient)(nil).ExposeBlockDevice), dpuStatus, spec, parameters)
}

// ExposeFSDevice mocks base method.
func (m *MockClient) ExposeFSDevice(deviceName string, dpuStatus v1alpha1.VolumeAttachmentStatusDPU, parameters map[string]string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExposeFSDevice", deviceName, dpuStatus, parameters)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ExposeFSDevice indicates an expected call of ExposeFSDevice.
func (mr *MockClientMockRecorder) ExposeFSDevice(deviceName, dpuStatus, parameters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExposeFSDevice", reflect.TypeOf((*MockClient)(nil).ExposeFSDevice), deviceName, dpuStatus, parameters)
}
