apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUService
metadata:
  name: vpc-ovn-node
  namespace: dpf-operator-system
spec:
  serviceID: vpc-ovn-node
  helmChart:
    source:
      repoURL: oci://example.com/chart
      version: v0.1.0
      chart: dpf-vpc-ovn
    values:
      dpu:
        vpcOVNNode:
          enabled: true
          initContainers:
            vpcOVNDpuProvisioner:
              env:
                ovnSbEndpoint: "tcp:$CONTROL_PLANE_IP:30642"
          ipRequests:
            - name: "vtep"
              poolName: "vpc-ippool-vtep"
              allocateIPWithIndex: 1
            - name: "gateway"
              poolName: "vpc-ippool-gateway"
              allocateIPWithIndex: 1
