apiVersion: v1
kind: ConfigMap
metadata:
  name: bfb-registry-config
  labels:
data:
  nginx.conf: |
    error_log  /dev/stderr notice;

    load_module /usr/local/nginx/modules/ngx_http_concat_module.so;

    worker_processes  auto;

    events {
        worker_connections  1024;
    }

    pid /nginx/nginx.pid;

    http {
        include       /usr/local/nginx/conf/mime.types;
        default_type  application/octet-stream;

        # Set all temp paths to use /nginx directory
        client_body_temp_path /nginx/client_body;
        proxy_temp_path /nginx/proxy;
        fastcgi_temp_path /nginx/fastcgi;
        uwsgi_temp_path /nginx/uwsgi;
        scgi_temp_path /nginx/scgi;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" $status';
        access_log  /dev/stdout  main;

        sendfile        on;
        keepalive_timeout  65;

        server {
            listen       ${NGINX_PORT};
            server_name  _;

            location / {
                root   html;
                index  index.html index.htm;
            }

            location /bfb {
                root /;
                concat on;
                concat_max_files 20;
                concat_types application/octet-stream;
                concat_types *;
                concat_unique off;
            }
        }
    }

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bfb-registry
  labels:
spec:
  template:
    metadata:
      labels:
    spec:
      hostNetwork: true
      containers:
      - name: nginx
        image: bfb-registry
        env:
        - name: NGINX_PORT
          value: "8080"
        command:
        - /bin/sh
        - -c
        - envsubst '$NGINX_PORT' < /nginx/nginx.conf.template > /nginx/nginx.conf && /usr/local/nginx/sbin/nginx -c /nginx/nginx.conf -g "daemon off;"
        volumeMounts:
        - name: bfb-registry-config
          mountPath: /nginx/nginx.conf.template
          subPath: nginx.conf
        - mountPath: /bfb
          name: bfb-volume
      volumes:
      - name: bfb-registry-config
        configMap:
          name: bfb-registry-config
      - name: bfb-volume
        persistentVolumeClaim:
          claimName: bfb-pvc