// /*
// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.
// */
//

// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab-master.nvidia.com/doca-platform-foundation/ovn-vpc/ovn/topology (interfaces: Manager)
//
// Generated by this command:
//
//	mockgen -copyright_file ../../hack/boilerplate.go.txt -package mock -destination mock/Manager.go . Manager
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/nvidia/doca-platform/api/dpuservice/v1alpha1"
	v1alpha10 "github.com/nvidia/doca-platform/api/vpc/v1alpha1"
	topology "gitlab-master.nvidia.com/doca-platform-foundation/ovn-vpc/ovn/topology"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	types "k8s.io/apimachinery/pkg/types"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// ApplyTopology mocks base method.
func (m *MockManager) ApplyTopology(ctx context.Context, vpc *v1alpha10.DPUVPC, networks []*v1alpha10.DPUVirtualNetwork, nodes []*v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyTopology", ctx, vpc, networks, nodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyTopology indicates an expected call of ApplyTopology.
func (mr *MockManagerMockRecorder) ApplyTopology(ctx, vpc, networks, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyTopology", reflect.TypeOf((*MockManager)(nil).ApplyTopology), ctx, vpc, networks, nodes)
}

// ListServiceInterfaces mocks base method.
func (m *MockManager) ListServiceInterfaces(ctx context.Context) ([]topology.ServiceInterfacRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServiceInterfaces", ctx)
	ret0, _ := ret[0].([]topology.ServiceInterfacRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServiceInterfaces indicates an expected call of ListServiceInterfaces.
func (mr *MockManagerMockRecorder) ListServiceInterfaces(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServiceInterfaces", reflect.TypeOf((*MockManager)(nil).ListServiceInterfaces), ctx)
}

// ListVPCs mocks base method.
func (m *MockManager) ListVPCs(ctx context.Context) ([]types.NamespacedName, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVPCs", ctx)
	ret0, _ := ret[0].([]types.NamespacedName)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVPCs indicates an expected call of ListVPCs.
func (mr *MockManagerMockRecorder) ListVPCs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVPCs", reflect.TypeOf((*MockManager)(nil).ListVPCs), ctx)
}

// PlugServiceInterface mocks base method.
func (m *MockManager) PlugServiceInterface(ctx context.Context, vpc *v1alpha10.DPUVPC, vn *v1alpha10.DPUVirtualNetwork, node *v1.Node, si *v1alpha1.ServiceInterface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlugServiceInterface", ctx, vpc, vn, node, si)
	ret0, _ := ret[0].(error)
	return ret0
}

// PlugServiceInterface indicates an expected call of PlugServiceInterface.
func (mr *MockManagerMockRecorder) PlugServiceInterface(ctx, vpc, vn, node, si any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlugServiceInterface", reflect.TypeOf((*MockManager)(nil).PlugServiceInterface), ctx, vpc, vn, node, si)
}

// RemoveTopology mocks base method.
func (m *MockManager) RemoveTopology(ctx context.Context, vpc *v1alpha10.DPUVPC) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTopology", ctx, vpc)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTopology indicates an expected call of RemoveTopology.
func (mr *MockManagerMockRecorder) RemoveTopology(ctx, vpc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTopology", reflect.TypeOf((*MockManager)(nil).RemoveTopology), ctx, vpc)
}

// UnplugServiceInterface mocks base method.
func (m *MockManager) UnplugServiceInterface(ctx context.Context, vn *v1alpha10.DPUVirtualNetwork, si *v1alpha1.ServiceInterface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnplugServiceInterface", ctx, vn, si)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnplugServiceInterface indicates an expected call of UnplugServiceInterface.
func (mr *MockManagerMockRecorder) UnplugServiceInterface(ctx, vn, si any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnplugServiceInterface", reflect.TypeOf((*MockManager)(nil).UnplugServiceInterface), ctx, vn, si)
}
