{
 "title": "Controller Runtime",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(dpf_controller_runtime_active_workers{job=\"doca-platform-framework\"},pod)"
    }
   },
   {
    "name": "Container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{node=~\"^$Node$\",pod=~\"^$Pod$\"},container)"
    }
   },
   {
    "name": "Controller",
    "label": "Controller",
    "query": {
     "query": "label_values(dpf_controller_runtime_active_workers,controller)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_info{pod=~\"$Pod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\"$Pod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_status_phase{pod=~\"$Pod\"}==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"$Pod\",}[5m])) by (pod)\n",
       "legendFormat": "{{pod}}: {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Working Set Bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(container_memory_working_set_bytes{pod=~\"$Pod\"}) by (pod)",
       "legendFormat": "{{pod}}: {{container}}"
      }
     ]
    },
    {
     "title": "Memory Cached",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(container_memory_cache{pod=~\"$Pod\"}) by (pod)",
       "legendFormat": "{{pod}}: {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Transmit Bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(rate(container_network_transmit_bytes_total{pod=~\"$Pod\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network Receive Bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(rate(container_network_receive_bytes_total{pod=~\"$Pod\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network Transmit Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(rate(container_network_transmit_errors_total{pod=~\"$Pod\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network Receive Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(rate(container_network_receive_errors_total{pod=~\"$Pod\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller Active Workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(dpf_controller_runtime_active_workers{pod=~\"$Pod\",controller=~\"$Controller\"}) by (pod,controller)",
       "legendFormat": "{{pod}}: {{controller}}"
      }
     ]
    },
    {
     "title": "Controller Worker Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(dpf_controller_runtime_active_workers{pod=~\"$Pod\",controller=~\"$Controller\"}) by (pod,controller) / sum(dpf_controller_runtime_max_concurrent_reconciles{pod=~\"$Pod\",controller=~\"$Controller\"}) by (pod,controller)",
       "legendFormat": "{{pod}}: {{controller}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Reconcile Results",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconcile Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(dpf_controller_runtime_reconcile_total{pod=~\"$Pod\",controller=~\"$Controller\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Reconcile Total by Controller",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(dpf_controller_runtime_reconcile_total{pod=~\"$Pod\",controller=~\"$Controller\"}[5m])) by (pod,controller)",
       "legendFormat": "{{pod}}: {{controller}}"
      }
     ]
    },
    {
     "title": "Reconcile Total by Result",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(dpf_controller_runtime_reconcile_total{pod=~\"$Pod\",controller=~\"$Controller\"}[5m])) by (pod,result)",
       "legendFormat": "{{pod}}: {{result}}"
      }
     ]
    },
    {
     "title": "Reconcile Total by Controller, Result",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(dpf_controller_runtime_reconcile_total{pod=~\"$Pod\",controller=~\"$Controller\"}[5m])) by (pod,controller,result)",
       "legendFormat": "{{pod}}: {{controller}}: {{result}}"
      }
     ]
    },
    {
     "title": "Reconcile Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(dpf_controller_runtime_reconcile_errors_total{pod=~\"$Pod\",controller=~\"$Controller\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Reconcile Errors by Controller",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(dpf_controller_runtime_reconcile_errors_total{pod=~\"$Pod\",controller=~\"$Controller\"}[5m])) by (pod,controller)",
       "legendFormat": "{{pod}}: {{controller}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Reconcile Durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconcile Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(dpf_controller_runtime_reconcile_time_seconds_sum{pod=~\"$Pod\"}[5m])) by (pod) / sum(rate(dpf_controller_runtime_reconcile_time_seconds_count{pod=~\"$Pod\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Reconcile Duration Quantils",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(dpf_controller_runtime_reconcile_time_seconds_bucket{pod=~\"$Pod\"}[5m])) by (pod, le))",
       "legendFormat": "P50 {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dpf_controller_runtime_reconcile_time_seconds_bucket{pod=~\"$Pod\"}[5m])) by (pod, le))",
       "legendFormat": "P90 {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dpf_controller_runtime_reconcile_time_seconds_bucket{pod=~\"$Pod\"}[5m])) by (pod, le))",
       "legendFormat": "P99 {{pod}}"
      }
     ]
    },
    {
     "title": "Reconcile Duration by Controller",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(dpf_controller_runtime_reconcile_time_seconds_sum{pod=~\"$Pod\",controller=~\"$Controller\"}[5m])) by (pod,controller) / sum(rate(dpf_controller_runtime_reconcile_time_seconds_count{pod=~\"$Pod\",controller=~\"$Controller\"}[5m])) by (pod,controller)",
       "legendFormat": "{{pod}}: {{controller}}"
      }
     ]
    },
    {
     "title": "Reconcile Duration Quantils by Controller",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(dpf_controller_runtime_reconcile_time_seconds_bucket{pod=~\"$Pod\",controller=~\"$Controller\"}[5m])) by (pod, controller, le))",
       "legendFormat": "P50 {{pod}} {{controller}} "
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dpf_controller_runtime_reconcile_time_seconds_bucket{pod=~\"$Pod\",controller=~\"$Controller\"}[5m])) by (pod, controller, le))",
       "legendFormat": "P90 {{pod}} {{controller}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dpf_controller_runtime_reconcile_time_seconds_bucket{pod=~\"$Pod\",controller=~\"$Controller\"}[5m])) by (pod, controller, le))",
       "legendFormat": "P99 {{pod}} {{controller}} "
      }
     ]
    },
    {
     "title": "Reconcile Duration Buckets",
     "type": "heatmap",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "rate(dpf_controller_runtime_reconcile_time_seconds_bucket{pod=~\"$Pod\", controller=~\"$Controller\"}[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workqueue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workqueue Depth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "dpf_workqueue_depth{pod=~\"$Pod\",name=~\"$Controller\"}",
       "legendFormat": "{{pod}}: {{name}}"
      }
     ]
    },
    {
     "title": "Workqueue Adds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(dpf_workqueue_adds_total{pod=~\"$Pod\",name=~\"$Controller\"}[5m])",
       "legendFormat": "{{pod}}: {{name}}"
      }
     ]
    },
    {
     "title": "Workqueue Retries",
     "type": "timeseries",
     "description": "Total number of retries handled by workqueue. In controller-runtime the retry metric is observed when an item is added to the queue because of RequeueAfter.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(dpf_workqueue_retries_total{pod=~\"$Pod\",name=~\"$Controller\"}[5m])",
       "legendFormat": "{{pod}}: {{name}}"
      }
     ]
    },
    {
     "title": "Workqueue Longest Running Processor",
     "type": "timeseries",
     "description": "How many seconds has the longest running processor for workqueue been running.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dpf_workqueue_longest_running_processor_seconds{pod=~\"$Pod\",name=~\"$Controller\"}",
       "legendFormat": "{{pod}}: {{name}}"
      }
     ]
    },
    {
     "title": "Workqueue Unfinished Work",
     "type": "timeseries",
     "description": "How many seconds of work has been done that is in progress and hasn't been observed by work_duration. Large values indicate stuck threads. One can deduce the number of stuck threads by observing the rate at which this increases.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dpf_workqueue_unfinished_work_seconds{pod=~\"$Pod\",name=~\"$Controller\"}",
       "legendFormat": "{{pod}}: {{name}}"
      }
     ]
    },
    {
     "title": "Workqueue Work Duration Quantils",
     "type": "timeseries",
     "description": "How long in seconds processing an item from workqueue takes",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(dpf_workqueue_work_duration_seconds_bucket{pod=~\"$Pod\",name=~\"$Controller\"}[5m])) by (pod, name, le))",
       "legendFormat": "P50 {{pod}} {{name}} "
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dpf_workqueue_work_duration_seconds_bucket{pod=~\"$Pod\",name=~\"$Controller\"}[5m])) by (pod, name, le))",
       "legendFormat": "P90 {{pod}} {{name}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dpf_workqueue_work_duration_seconds_bucket{pod=~\"$Pod\",name=~\"$Controller\"}[5m])) by (pod, name, le))",
       "legendFormat": "P99 {{pod}} {{name}} "
      }
     ]
    },
    {
     "title": "Workqueue Queue Duration Quantils",
     "type": "timeseries",
     "description": "How long in seconds an item stays in workqueue before being requested",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(dpf_workqueue_queue_duration_seconds_bucket{pod=~\"$Pod\",name=~\"$Controller\"}[5m])) by (pod, name, le))",
       "legendFormat": "P50 {{pod}} {{name}} "
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dpf_workqueue_queue_duration_seconds_bucket{pod=~\"$Pod\",name=~\"$Controller\"}[5m])) by (pod, name, le))",
       "legendFormat": "P90 {{pod}} {{name}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dpf_workqueue_queue_duration_seconds_bucket{pod=~\"$Pod\",name=~\"$Controller\"}[5m])) by (pod, name, le))",
       "legendFormat": "P99 {{pod}} {{name}} "
      }
     ]
    },
    {
     "title": "Workqueue Work Duration",
     "type": "heatmap",
     "description": "How long in seconds processing an item from workqueue takes",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "rate(dpf_workqueue_work_duration_seconds_bucket{pod=~\"$Pod\", name=~\"$Controller\"}[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Workqueue Queue Duration",
     "type": "heatmap",
     "description": "How long in seconds an item stays in workqueue before being requested",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "rate(dpf_workqueue_queue_duration_seconds_bucket{pod=~\"$Pod\", name=~\"$Controller\"}[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Webhook",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Webhook Total by Path",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(dpf_controller_runtime_webhook_requests_total{pod=~\"$Pod\",webhook=~\"/mutate-.*\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}: Mutate"
      },
      {
       "expr": "sum(rate(dpf_controller_runtime_webhook_requests_total{pod=~\"$Pod\",webhook=~\"/validate-.*\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}: Validate"
      },
      {
       "expr": "sum(rate(dpf_controller_runtime_webhook_requests_total{pod=~\"$Pod\",webhook=~\"/convert\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}: Convert"
      }
     ]
    },
    {
     "title": "Webhook Total by Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(dpf_controller_runtime_webhook_requests_total{pod=~\"$Pod\"}[5m])) by (pod,code,webhook) > 0",
       "legendFormat": "{{pod}}: {{code}}: {{webhook}}"
      }
     ]
    },
    {
     "title": "Webhook Total by Code != 200",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(dpf_controller_runtime_webhook_requests_total{pod=~\"$Pod\",code!=\"200\"}[5m])) by (pod,code,webhook) > 0",
       "legendFormat": "{{pod}}: {{code}}: {{webhook}}"
      }
     ]
    },
    {
     "title": "Webhook Total by Path",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(dpf_controller_runtime_webhook_latency_seconds_sum{pod=~\"$Pod\"}[5m])) by (pod,webhook) / sum(rate(dpf_controller_runtime_webhook_latency_seconds_count{pod=~\"$Pod\"}[5m])) by (pod,webhook) > 0",
       "legendFormat": "{{pod}}: {{code}}: {{webhook}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Requests by Method, Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(dpf_rest_client_requests_total{pod=~\"$Pod\"}[5m])) by (pod, code, method) > 0",
       "legendFormat": "{{pod}}: {{method}}: {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proccess Open File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "dpf_process_open_fds{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Proccess Open File Descriptors Derivative",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "deriv(dpf_process_open_fds{pod=~\"$Pod\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "dpf_go_goroutines{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "dpf_go_memstats_sys_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: memstats sys"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "dpf_go_memstats_stack_inuse_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: stack inuse"
      },
      {
       "expr": "dpf_go_memstats_stack_sys_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: stack sys"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "dpf_go_memstats_heap_alloc_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: heap alloc"
      },
      {
       "expr": "dpf_go_memstats_heap_sys_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: heap sys"
      },
      {
       "expr": "dpf_go_memstats_heap_idle_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: heap idle"
      },
      {
       "expr": "dpf_go_memstats_heap_inuse_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: heap inuse"
      },
      {
       "expr": "dpf_go_memstats_heap_released_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: heap released"
      }
     ]
    },
    {
     "title": "Memory in Off-Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "dpf_go_memstats_mspan_inuse_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: mspan inuse"
      },
      {
       "expr": "dpf_go_memstats_mspan_sys_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: mspan sys"
      },
      {
       "expr": "dpf_go_memstats_mcache_inuse_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: mcache inuse"
      },
      {
       "expr": "dpf_go_memstats_mcache_sys_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: mcache sys"
      },
      {
       "expr": "dpf_go_memstats_buck_hash_sys_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: bucket hash sys"
      },
      {
       "expr": "dpf_go_memstats_gc_sys_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: gc sys"
      },
      {
       "expr": "dpf_go_memstats_other_sys_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: other sys"
      },
      {
       "expr": "dpf_go_memstats_next_gc_bytes{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: next gc"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "dpf_go_memstats_mallocs_total{pod=~\"$Pod\"} - dpf_go_memstats_frees_total{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Pointer Dereferences",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(dpf_go_memstats_lookups_total{pod=~\"$Pod\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(dpf_go_memstats_mallocs_total{pod=~\"$Pod\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Bytes Allocated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(dpf_go_memstats_alloc_bytes_total{pod=~\"$Pod\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "dpf_go_gc_duration_seconds{pod=~\"$Pod\"}",
       "legendFormat": "{{pod}}: {{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}