{
 "title": "DOCA Platform Framework - Performance",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dpf_dpu_conditions",
    "label": "DPU Conditions",
    "query": {
     "query": "label_values(dpf_dpu_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpuservice_conditions",
    "label": "DPUService Conditions",
    "query": {
     "query": "label_values(dpf_dpuservice_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpfoperatorconfig_conditions",
    "label": "DPFOperatorConfig Conditions",
    "query": {
     "query": "label_values(dpf_dpfoperatorconfig_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpuserviceinterface_conditions",
    "label": "DPUServiceInterface Conditions",
    "query": {
     "query": "label_values(dpf_dpuserviceinterface_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpuservicechain_conditions",
    "label": "DPUServiceChain Conditions",
    "query": {
     "query": "label_values(dpf_dpuservicechain_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpuserviceipam_conditions",
    "label": "DPUServiceIPAM Conditions",
    "query": {
     "query": "label_values(dpf_dpuserviceipam_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpudeployment_conditions",
    "label": "DPUDeployment Conditions",
    "query": {
     "query": "label_values(dpf_dpudeployment_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpuservicecredentialrequest_conditions",
    "label": "DPUServiceCredentialRequest Conditions",
    "query": {
     "query": "label_values(dpf_dpuservicecredentialrequest_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpucluster_conditions",
    "label": "DPUCluster Conditions",
    "query": {
     "query": "label_values(dpf_dpucluster_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpudevice_conditions",
    "label": "DPUDevice Conditions",
    "query": {
     "query": "label_values(dpf_dpudevice_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpunode_conditions",
    "label": "DPUNode Conditions",
    "query": {
     "query": "label_values(dpf_dpunode_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpunodemaintenance_conditions",
    "label": "DPUNodeMaintenance Conditions",
    "query": {
     "query": "label_values(dpf_dpunodemaintenance_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpuservicenad_conditions",
    "label": "DPUServiceNAD Conditions",
    "query": {
     "query": "label_values(dpf_dpuservicenad_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpuset_conditions",
    "label": "DPUSet Conditions",
    "query": {
     "query": "label_values(dpf_dpuset_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpustoragepolicy_conditions",
    "label": "DPUStoragePolicy Conditions",
    "query": {
     "query": "label_values(dpf_dpustoragepolicy_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpustoragevendor_conditions",
    "label": "DPUStorageVendor Conditions",
    "query": {
     "query": "label_values(dpf_dpustoragevendor_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpuvolume_conditions",
    "label": "DPUVolume Conditions",
    "query": {
     "query": "label_values(dpf_dpuvolume_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpuvolumeattachment_conditions",
    "label": "DPUVolumeAttachment Conditions",
    "query": {
     "query": "label_values(dpf_dpuvolumeattachment_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpuvirtualnetwork_conditions",
    "label": "DPUVirtualNetwork Conditions",
    "query": {
     "query": "label_values(dpf_dpuvirtualnetwork_status_conditions,type)"
    }
   },
   {
    "name": "dpf_dpuvpc_conditions",
    "label": "DPUVPC Conditions",
    "query": {
     "query": "label_values(dpf_dpuvpc_status_conditions,type)"
    }
   },
   {
    "name": "dpf_servicechain_conditions",
    "query": {
     "query": "label_values(dpf_servicechain_status_conditions,type)"
    }
   },
   {
    "name": "dpf_servicechainset_conditions",
    "query": {
     "query": "label_values(dpf_servicechainset_status_conditions,type)"
    }
   },
   {
    "name": "dpf_serviceinterface_conditions",
    "query": {
     "query": "label_values(dpf_serviceinterface_status_conditions,type)"
    }
   },
   {
    "name": "dpf_serviceinterfaceset_conditions",
    "query": {
     "query": "label_values(dpf_serviceinterfaceset_status_conditions,type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Performance > DPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPU time until $dpf_dpu_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "repeat": "dpf_dpu_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpu_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpu_conditions\"} - on(uid) group_left () dpf_dpu_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPFOperatorConfig",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPFOperatorConfig time until $dpf_dpfoperatorconfig_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 201 },
     "repeat": "dpf_dpfoperatorconfig_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpfoperatorconfig_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpfoperatorconfig_conditions\"} - on(uid) group_left () dpf_dpfoperatorconfig_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUCluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUCluster time until $dpf_dpucluster_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 290 },
     "repeat": "dpf_dpucluster_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpucluster_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpucluster_conditions\"} - on(uid) group_left () dpf_dpucluster_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUDeployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUDeployment time until $dpf_dpudeployment_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 291 },
     "repeat": "dpf_dpudeployment_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpudeployment_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpudeployment_conditions\"} - on(uid) group_left () dpf_dpudeployment_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUService time until $dpf_dpuservice_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 292 },
     "repeat": "dpf_dpuservice_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpuservice_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpuservice_conditions\"} - on(uid) group_left () dpf_dpuservice_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUServiceCredentialRequest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUServiceCredentialRequest time until $dpf_dpuservicecredentialrequest_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 293 },
     "repeat": "dpf_dpuservicecredentialrequest_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpuservicecredentialrequest_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpuservicecredentialrequest_conditions\"} - on(uid) group_left () dpf_dpuservicecredentialrequest_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUServiceChain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUServiceChain time until $dpf_dpuservicechain_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 294 },
     "repeat": "dpf_dpuservicechain_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpuservicechain_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpuservicechain_conditions\"} - on(uid) group_left () dpf_dpuservicechain_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUServiceInterface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUServiceInterface time until $dpf_dpuserviceinterface_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 295 },
     "repeat": "dpf_dpuserviceinterface_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpuserviceinterface_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpuserviceinterface_conditions\"} - on(uid) group_left () dpf_dpuserviceinterface_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUServiceIPAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUServiceIPAM time until $dpf_dpuserviceipam_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 296 },
     "repeat": "dpf_dpuserviceipam_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpuserviceipam_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpuserviceipam_conditions\"} - on(uid) group_left () dpf_dpuserviceipam_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUDevice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUDevice time until $dpf_dpudevice_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 297 },
     "repeat": "dpf_dpudevice_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpudevice_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpudevice_conditions\"} - on(uid) group_left () dpf_dpudevice_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUNode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUNode time until $dpf_dpunode_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 298 },
     "repeat": "dpf_dpunode_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpunode_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpunode_conditions\"} - on(uid) group_left () dpf_dpunode_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUNodeMaintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUNodeMaintenance time until $dpf_dpunodemaintenance_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 299 },
     "repeat": "dpf_dpunodemaintenance_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpunodemaintenance_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpunodemaintenance_conditions\"} - on(uid) group_left () dpf_dpunodemaintenance_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUServiceNAD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUServiceNAD time until $dpf_dpuservicenad_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 300 },
     "repeat": "dpf_dpuservicenad_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpuservicenad_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpuservicenad_conditions\"} - on(uid) group_left () dpf_dpuservicenad_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUSet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUSet time until $dpf_dpuset_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 301 },
     "repeat": "dpf_dpuset_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpuset_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpuset_conditions\"} - on(uid) group_left () dpf_dpuset_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUStoragePolicy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUStoragePolicy time until $dpf_dpustoragepolicy_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 302 },
     "repeat": "dpf_dpustoragepolicy_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpustoragepolicy_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpustoragepolicy_conditions\"} - on(uid) group_left () dpf_dpustoragepolicy_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUStorageVendor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUStorageVendor time until $dpf_dpustoragevendor_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 303 },
     "repeat": "dpf_dpustoragevendor_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpustoragevendor_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpustoragevendor_conditions\"} - on(uid) group_left () dpf_dpustoragevendor_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUVolume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUVolume time until $dpf_dpuvolume_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 304 },
     "repeat": "dpf_dpuvolume_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpuvolume_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpuvolume_conditions\"} - on(uid) group_left () dpf_dpuvolume_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUVolumeAttachment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUVolumeAttachment time until $dpf_dpuvolumeattachment_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 305 },
     "repeat": "dpf_dpuvolumeattachment_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpuvolumeattachment_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpuvolumeattachment_conditions\"} - on(uid) group_left () dpf_dpuvolumeattachment_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUVirtualNetwork",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUVirtualNetwork time until $dpf_dpuvirtualnetwork_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 306 },
     "repeat": "dpf_dpuvirtualnetwork_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpuvirtualnetwork_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpuvirtualnetwork_conditions\"} - on(uid) group_left () dpf_dpuvirtualnetwork_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUVPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUVPC time until $dpf_dpuvpc_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 307 },
     "repeat": "dpf_dpuvpc_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_dpuvpc_status_condition_last_transition_time{status=\"True\",type=\"$dpf_dpuvpc_conditions\"} - on(uid) group_left () dpf_dpuvpc_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > ServiceChain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "ServiceChain time until $dpf_servicechain_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 319 },
     "repeat": "dpf_dpuservicechain_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_servicechain_status_condition_last_transition_time{status=\"True\",type=\"$dpf_servicechain_conditions\"} - on(uid) group_left () dpf_servicechain_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > ServiceChainSet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "ServiceChainSet time until $dpf_servicechainset_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 320 },
     "repeat": "dpf_dpuservicechain_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_servicechainset_status_condition_last_transition_time{status=\"True\",type=\"$dpf_servicechainset_conditions\"} - on(uid) group_left () dpf_servicechainset_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > ServiceInterface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "ServiceInterface time until $dpf_serviceinterface_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 321 },
     "repeat": "dpf_dpuservicechain_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_serviceinterface_status_condition_last_transition_time{status=\"True\",type=\"$dpf_serviceinterface_conditions\"} - on(uid) group_left () dpf_serviceinterface_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > ServiceInterfaceSet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "ServiceInterfaceSet time until $dpf_serviceinterfaceset_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 322 },
     "repeat": "dpf_dpuservicechain_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpf_serviceinterfaceset_status_condition_last_transition_time{status=\"True\",type=\"$dpf_serviceinterfaceset_conditions\"} - on(uid) group_left () dpf_serviceinterfaceset_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Conditions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPFOperatorConfig by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum (dpf_dpfoperatorconfig_info)",
       "legendFormat": "All"
      },
      {
       "expr": "sum(dpf_dpfoperatorconfig_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpfoperatorconfig_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUDeployment by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
     "targets": [
      { "expr": "sum (dpf_dpudeployment_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpf_dpudeployment_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpudeployment_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUService by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
     "targets": [
      { "expr": "sum (dpf_dpuservice_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpf_dpuservice_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpuservice_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUServiceChain by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
     "targets": [
      { "expr": "sum (dpf_dpuservicechain_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpf_dpuservicechain_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpuservicechain_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUServiceInterface by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum (dpf_dpuserviceinterface_info)",
       "legendFormat": "All"
      },
      {
       "expr": "sum(dpf_dpuserviceinterface_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpuserviceinterface_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUServiceIPAM by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
     "targets": [
      { "expr": "sum (dpf_dpuserviceipam_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpf_dpuserviceipam_status_condition{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpuserviceipam_status_condition{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPU by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
     "targets": [
      { "expr": "sum (dpf_dpu_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpf_dpu_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpu_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUDevice by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
     "targets": [
      { "expr": "sum (dpf_dpudevice_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpf_dpudevice_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpudevice_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUNode by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
     "targets": [
      { "expr": "sum (dpf_dpunode_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpf_dpunode_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpunode_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUNodeMaintenance by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
     "targets": [
      {
       "expr": "sum (dpf_dpunodemaintenance_info)",
       "legendFormat": "All"
      },
      {
       "expr": "sum(dpf_dpunodemaintenance_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpunodemaintenance_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUServiceNAD by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
     "targets": [
      { "expr": "sum (dpf_dpuservicenad_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpf_dpuservicenad_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpuservicenad_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUSet by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
     "targets": [
      { "expr": "sum (dpf_dpuset_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpf_dpuset_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpuset_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUStoragePolicy by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "sum (dpf_dpustoragepolicy_info)",
       "legendFormat": "All"
      },
      {
       "expr": "sum(dpf_dpustoragepolicy_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpustoragepolicy_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUStorageVendor by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
     "targets": [
      {
       "expr": "sum (dpf_dpustoragevendor_info)",
       "legendFormat": "All"
      },
      {
       "expr": "sum(dpf_dpustoragevendor_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpustoragevendor_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUVolume by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
     "targets": [
      { "expr": "sum (dpf_dpuvolume_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpf_dpuvolume_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpuvolume_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUVolumeAttachment by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 49 },
     "targets": [
      {
       "expr": "sum (dpf_dpuvolumeattachment_info)",
       "legendFormat": "All"
      },
      {
       "expr": "sum(dpf_dpuvolumeattachment_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpuvolumeattachment_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUVirtualNetwork by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sum (dpf_dpuvirtualnetwork_info)",
       "legendFormat": "All"
      },
      {
       "expr": "sum(dpf_dpuvirtualnetwork_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpuvirtualnetwork_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUVPC by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
     "targets": [
      { "expr": "sum (dpf_dpuvpc_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpf_dpuvpc_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpf_dpuvpc_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    }
   ]
  },
  {
   "title": "Phases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPU by status phase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 310 },
     "targets": [
      {
       "expr": "sum(dpf_dpu_status_phase == 1) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "BFB by status phase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 310 },
     "targets": [
      {
       "expr": "sum(dpf_bfb_status_phase == 1) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    }
   ]
  }
 ]
}