{
 "title": "Kubernetes APIServer Requests",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{node=~\"^$Node$\"},pod)"
    }
   },
   {
    "name": "Group",
    "label": "Group",
    "query": {
     "query": "label_values(apiserver_request_total,group)"
    }
   },
   {
    "name": "Version",
    "label": "Version",
    "query": {
     "query": "label_values(apiserver_request_total,version)"
    }
   },
   {
    "name": "Resource",
    "label": "Resource",
    "query": {
     "query": "label_values(apiserver_request_total,resource)"
    }
   },
   {
    "name": "Subresource",
    "label": "Subresource",
    "query": {
     "query": "label_values(apiserver_request_total,subresource)"
    }
   },
   {
    "name": "Verb",
    "label": "Verb",
    "query": {
     "query": "label_values(apiserver_request_total,verb)"
    }
   }
  ]
 },
 "panels": [
  { "title": "APIServer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests (all)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{group=~\"$Group\",version=~\"$Version\",resource=~\"$Resource\",subresource=~\"$Subresource\",verb=~\"$Verb\"}[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Requests (dryrun)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{group=~\"$Group\",version=~\"$Version\",resource=~\"$Resource\",subresource=~\"$Subresource\",verb=~\"$Verb\",dry_run!=\"\"}[5m])) by (dry_run)",
     "legendFormat": "dry_run = {{dry_run}}"
    }
   ]
  },
  {
   "title": "Requests by Resource (all)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{group=~\"$Group\",version=~\"$Version\",resource=~\"$Resource\",subresource=~\"$Subresource\",verb=~\"$Verb\"}[5m])) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Requests by Resource (dryrun)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{group=~\"$Group\",version=~\"$Version\",resource=~\"$Resource\",subresource=~\"$Subresource\",verb=~\"$Verb\",dry_run!=\"\"}[5m])) by (resource)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Resource, Subresource, Verb (all)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{group=~\"$Group\",version=~\"$Version\",resource=~\"$Resource\",subresource=~\"$Subresource\",verb=~\"$Verb\"}[5m])) by (resource,subresource,verb) > 0",
     "legendFormat": "{{resource}} {{subresource}} {{verb}}"
    }
   ]
  },
  {
   "title": "Requests by Resource, Subresource, Verb (dryrun)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{group=~\"$Group\",version=~\"$Version\",resource=~\"$Resource\",subresource=~\"$Subresource\",verb=~\"$Verb\",dry_run!=\"\"}[5m])) by (resource,subresource,verb) > 0",
     "legendFormat": "{{resource}} {{subresource}} {{verb}}"
    }
   ]
  },
  { "title": "Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Client Requests by Pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{host=\"10.96.0.1:443\",pod=~\"$Pod\",method=~\"$Verb\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Requests by Pod, Method",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{host=\"10.96.0.1:443\",pod=~\"$Pod\"}[5m])) by (pod,method)",
     "legendFormat": "{{pod}}: {{method}}"
    }
   ]
  }
 ]
}