{
 "title": "DOCA Platform Framework State",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dpu_conditions",
    "label": "DPU Conditions",
    "query": {
     "query": "label_values(dpu_status_conditions,type)"
    }
   },
   {
    "name": "dpuservice_conditions",
    "label": "DPUService Conditions",
    "query": {
     "query": "label_values(dpuservice_status_conditions,type)"
    }
   },
   {
    "name": "dpfoperatorconfig_conditions",
    "label": "DPFOperatorConfig Conditions",
    "query": {
     "query": "label_values(dpfoperatorconfig_status_conditions,type)"
    }
   },
   {
    "name": "dpuserviceinterface_conditions",
    "label": "DPUServiceInterface Conditions",
    "query": {
     "query": "label_values(dpuserviceinterface_status_conditions,type)"
    }
   },
   {
    "name": "dpuservicechain_conditions",
    "label": "DPUServiceChain Conditions",
    "query": {
     "query": "label_values(dpuservicechain_status_conditions,type)"
    }
   },
   {
    "name": "dpuserviceipam_conditions",
    "label": "DPUServiceIPAM Conditions",
    "query": {
     "query": "label_values(dpuserviceipam_status_conditions,type)"
    }
   },
   {
    "name": "dpudeployment_conditions",
    "label": "DPUDeployment Conditions",
    "query": {
     "query": "label_values(dpudeployment_status_conditions,type)"
    }
   },
   {
    "name": "dpuservicecredentialrequest_conditions",
    "label": "DPUServiceCredentialRequest Conditions",
    "query": {
     "query": "label_values(dpuservicecredentialrequest_status_conditions,type)"
    }
   },
   {
    "name": "dpucluster_conditions",
    "label": "DPUCluster Conditions",
    "query": {
     "query": "label_values(dpucluster_status_conditions,type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DPFOperatorConfig",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpfoperatorconfig_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpfoperatorconfig_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpfoperatorconfig_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUCluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpucluster_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpucluster_status_conditions{type=\"Created\"}) by (uid))",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpucluster_status_conditions{type=\"Created\"}) by (uid))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUDeployment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpudeployment_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpudeployment_status_conditions{type=\"Ready\"}) by (uid))",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpudeployment_status_conditions{type=\"Ready\"}) by (uid))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUService",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuservice_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuservice_status_conditions{type=\"Ready\"}) by (uid))",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuservice_status_conditions{type=\"Ready\"}) by (uid))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUServiceCredentialRequest",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuservicecredentialrequest_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuservicecredentialrequest_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuservicecredentialrequest_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUServiceChain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuservicechain_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuservicechain_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuservicechain_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUServiceInterface",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuserviceinterface_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuserviceinterface_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuserviceinterface_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUServiceIPAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuserviceipam_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuserviceipam_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuserviceipam_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpu_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpu_status_conditions{type=\"Ready\"}) by (uid)) or vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpu_status_conditions{type=\"Initialized\"}) by (uid))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "BFB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(bfb_status_phase{phase=\"Ready\"} == 1) by (uid)) * 100 / count(max(bfb_status_phase{phase=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "count(max(bfb_status_phase{phase=\"Ready\"}) by (uid))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Overview Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "DPUServices",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "dpuservice_info{}", "legendFormat": "Auto" },
    {
     "expr": "dpuservice_status_conditions{type=\"Ready\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DPUs",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "dpu_info{}", "legendFormat": "Auto" }
   ]
  },
  {
   "title": "DPUServiceCredentialRequests",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "dpuservicecredentialrequest_info",
     "legendFormat": "Auto"
    },
    {
     "expr": "dpuservicecredentialrequest_expiration * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "dpuservicecredentialrequest_issued_at * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}