
# The names in this values.yaml file must match the names of the subcharts under /charts
# These names must also match the names of the DPUServices that use the dpu-networking helm chart in the operator inventory.
flannel:
    enabled: false
    podCidr: 10.244.0.0/14
    flannel:
      image:
        tag: v0.27.2@sha256:782c111d55e850e8038cdaf35454987e6c170ae9b54d5b12895b02d45c908caf
      image_cni:
        tag: v1.7.1-flannel1@sha256:cb3176a2c9eae5fa0acd7f45397e706eacb4577dac33cad89f93b775ff5611df
multus:
    enabled: false
sriov-device-plugin:
    enabled: false
nvidia-k8s-ipam:
    enabled: false
ovs-cni:
    enabled: false
servicechainset-controller:
    enabled: false
sfc-controller:
    enabled: false
cni-installer:
    enabled: false
kube-state-metrics:
    enabled: false
node-problem-detector:
    enabled: false
opentelemetry-collector:
    enabled: false
