apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
automountServiceAccountToken: true
