{{ include "validate" . }}
{{- if .Values.host.vpcOVNController.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vpc-ovn-controller.fullname" . }}
  labels:
    {{- include "vpc-ovn-controller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "vpc-ovn-controller.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.host.vpcOVNController.replicas }}
  template:
    metadata:
      labels:
        {{- include "vpc-ovn-controller.selectorLabels" . | nindent 8 }}
        {{- with .Values.host.vpcOVNController.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- toYaml .Values.host.vpcOVNController.podAnnotations | nindent 8 }}
    spec:
      {{- with .Values.host.vpcOVNController.imagePullSecrets | default .Values.imagePullSecrets}}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.host.vpcOVNController.podSecurityContext | nindent 8 }}
      containers:
        - name: controller
          image: "{{ .Values.host.vpcOVNController.image.repository }}:{{ .Values.host.vpcOVNController.image.tag | default .Chart.AppVersion }}"
          command:
          - /vpc-ovn-controller
          {{- if .Values.host.vpcOVNController.topologyCleanerReconcilePeriod }}
          - --topology-cleaner-reconcile-period={{ .Values.host.vpcOVNController.topologyCleanerReconcilePeriod }}
          {{- end }}
          imagePullPolicy: {{ .Values.host.vpcOVNController.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.host.vpcOVNController.securityContext | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.host.vpcOVNController.resources | nindent 12 }}
      serviceAccountName: {{ include "vpc-ovn-controller.serviceAccountName" . }}
      {{- with .Values.host.vpcOVNController.nodeSelector | default dict }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.host.vpcOVNController.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.host.vpcOVNController.tolerations | default list }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vpc-ovn-controller.roleName" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - dpuclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - dpuserviceinterfaces
  - serviceinterfaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vpc.dpu.nvidia.com
  resources:
  - isolationclasses
  - dpuvirtualnetworks
  - dpuvpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpc.dpu.nvidia.com
  resources:
  - isolationclasses/finalizers
  - dpuvirtualnetworks/finalizers
  - dpuvpcs/finalizers
  verbs:
  - update
- apiGroups:
  - vpc.dpu.nvidia.com
  resources:
  - dpuvirtualnetworks/status
  - dpuvpcs/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
  name: {{ include "vpc-ovn-controller.roleBindingName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vpc-ovn-controller.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "vpc-ovn-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
  name: {{ include "vpc-ovn-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
