//go:build !ignore_autogenerated

/*
Copyright 2026 NVIDIA

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePluginResource) DeepCopyInto(out *DevicePluginResource) {
	*out = *in
	if in.ResourcePrefix != nil {
		in, out := &in.ResourcePrefix, &out.ResourcePrefix
		*out = new(string)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(DevicePluginResourceOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Ranges != nil {
		in, out := &in.Ranges, &out.Ranges
		*out = make([]FunctionRange, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePluginResource.
func (in *DevicePluginResource) DeepCopy() *DevicePluginResource {
	if in == nil {
		return nil
	}
	out := new(DevicePluginResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePluginResourceOptions) DeepCopyInto(out *DevicePluginResourceOptions) {
	*out = *in
	if in.IsRdma != nil {
		in, out := &in.IsRdma, &out.IsRdma
		*out = new(bool)
		**out = **in
	}
	if in.NeedVhostNet != nil {
		in, out := &in.NeedVhostNet, &out.NeedVhostNet
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePluginResourceOptions.
func (in *DevicePluginResourceOptions) DeepCopy() *DevicePluginResourceOptions {
	if in == nil {
		return nil
	}
	out := new(DevicePluginResourceOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionRange) DeepCopyInto(out *FunctionRange) {
	*out = *in
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(int32)
		**out = **in
	}
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionRange.
func (in *FunctionRange) DeepCopy() *FunctionRange {
	if in == nil {
		return nil
	}
	out := new(FunctionRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSRIOVDevicePluginConfig) DeepCopyInto(out *NodeSRIOVDevicePluginConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSRIOVDevicePluginConfig.
func (in *NodeSRIOVDevicePluginConfig) DeepCopy() *NodeSRIOVDevicePluginConfig {
	if in == nil {
		return nil
	}
	out := new(NodeSRIOVDevicePluginConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSRIOVDevicePluginConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSRIOVDevicePluginConfigList) DeepCopyInto(out *NodeSRIOVDevicePluginConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeSRIOVDevicePluginConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSRIOVDevicePluginConfigList.
func (in *NodeSRIOVDevicePluginConfigList) DeepCopy() *NodeSRIOVDevicePluginConfigList {
	if in == nil {
		return nil
	}
	out := new(NodeSRIOVDevicePluginConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSRIOVDevicePluginConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSRIOVDevicePluginConfigSpec) DeepCopyInto(out *NodeSRIOVDevicePluginConfigSpec) {
	*out = *in
	if in.DevicePluginResources != nil {
		in, out := &in.DevicePluginResources, &out.DevicePluginResources
		*out = make([]DevicePluginResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSRIOVDevicePluginConfigSpec.
func (in *NodeSRIOVDevicePluginConfigSpec) DeepCopy() *NodeSRIOVDevicePluginConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSRIOVDevicePluginConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSRIOVDevicePluginConfigStatus) DeepCopyInto(out *NodeSRIOVDevicePluginConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSRIOVDevicePluginConfigStatus.
func (in *NodeSRIOVDevicePluginConfigStatus) DeepCopy() *NodeSRIOVDevicePluginConfigStatus {
	if in == nil {
		return nil
	}
	out := new(NodeSRIOVDevicePluginConfigStatus)
	in.DeepCopyInto(out)
	return out
}
