---
apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUServiceTemplate
metadata:
  name: snap-controller
  namespace: dpf-operator-system
spec:
  deploymentServiceName: snap-controller
  helmChart:
    source:
      repoURL: $DPF_CHART_REPO
      version: $DPF_CHART_VERSION
      chart: dpf-storage
