apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUService
metadata:
  name: cni-installer
  namespace: dpf-operator-system
spec:
  security:
    privileged: true
  helmChart:
    source:
      repoURL: oci://example.com
      chart: cni-installer-chart
      version: v0.1.0
