---
apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUService
metadata:
  name: servicefunctionchainset-controller
  namespace: dpf-operator-system
spec:
  security:
    privileged: false
  helmChart:
    source:
      repoURL: oci://example.com
      chart: servicechain-chart
      version: v0.1.0
---
apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUServiceCredentialRequest
metadata:
  name: servicesetcontroller
  namespace: dpf-operator-system
spec:
  duration: 24h
  serviceAccount:
    name: example-serviceaccount-name
    namespace: example-serviceaccount-namespace
  targetCluster:
    name: example-cluster-name
    namespace: example-cluster-namespace
  type: tokenFile
  secret:
    name: example-secret-name
    namespace: example-secret-namespace
