/*
Copyright 2025 NVIDIA

Licensed under the Apache License, version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package util

import (
	"reflect"
	"testing"

	provisioningv1 "github.com/nvidia/doca-platform/api/provisioning/v1alpha1"
)

func TestVersionFromBFBFileWithTestData(t *testing.T) {
	expected := &provisioningv1.BFBVersions{
		ATF:  "4.11.0-45-g1fb6dd744",
		BSP:  "4.11.0.13611",
		DOCA: "3.0.0",
		UEFI: "4.11.0-62-g6cd3c6dfb3",
	}

	// This test file was generated by running:
	// strings  bfb-file.bfb |   grep -B 1000 "Members@odata.count"
	testFile := "../../testdata/test-bfb.bfb"
	versions, err := VersionFromBFBFile(testFile)
	if err != nil {
		t.Fatalf("VersionFromBFBFile failed on dynamically created test file: %v", err)
	}

	if !reflect.DeepEqual(versions, expected) {
		t.Errorf("Test file versions don't match expected. Got: %+v, Expected: %+v", versions, expected)
	}
}

func Test_formatDOCAVersion(t *testing.T) {
	tests := []struct {
		name    string
		version string
		want    string
		wantErr bool
	}{
		{
			name:    "valid version",
			version: "3.0.0058",
			want:    "3.0.0",
			wantErr: false,
		},
		{
			name:    "valid version with suffix",
			version: "3.0.0058-abdslsl",
			want:    "3.0.0",
			wantErr: false,
		},
		{
			name:    "error on empty version string",
			version: "",
			want:    "",
			wantErr: true,
		},
		{
			name:    "error on version with 2 components",
			version: "3.0",
			want:    "",
			wantErr: true,
		},
		{
			name:    "error on version with 4 components",
			version: "3.0.0.1",
			want:    "",
			wantErr: true,
		},
		{
			name:    "error on version with empty patchbuild component",
			version: "3.0.",
			want:    "",
			wantErr: true,
		},
		{
			name:    "error on version with non-numeric patchbuild component",
			version: "3.0.a0053",
			want:    "",
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := formatDOCAVersion(tt.version)
			if (err != nil) != tt.wantErr {
				t.Errorf("formatDOCAVersion() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if got != tt.want {
				t.Errorf("formatDOCAVersion() got = %v, want %v", got, tt.want)
			}
		})
	}
}
