apiVersion: v1
kind: Secret
metadata:
  name: $HELM_REPOSITORY_NAME
  namespace: dpf-operator-system
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: $HELM_REPOSITORY_NAME
  url: $HELM_REPOSITORY_URL
  type: helm
  username: $HELM_REPOSITORY_USERNAME
  password: $HELM_REPOSITORY_KEY
