/*
Copyright 2025 NVIDIA.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

import "github.com/ovn-org/libovsdb/model"

const GatewayChassisTable = "Gateway_Chassis"

// GatewayChassis defines an object in Gateway_Chassis table
type GatewayChassis struct {
	UUID        string            `ovsdb:"_uuid"`
	ChassisName string            `ovsdb:"chassis_name"`
	ExternalIDs map[string]string `ovsdb:"external_ids"`
	Name        string            `ovsdb:"name"`
	Options     map[string]string `ovsdb:"options"`
	Priority    int               `ovsdb:"priority"`
}

func (a *GatewayChassis) GetUUID() string {
	return a.UUID
}

func (a *GatewayChassis) GetChassisName() string {
	return a.ChassisName
}

func (a *GatewayChassis) GetExternalIDs() map[string]string {
	return a.ExternalIDs
}

func copyGatewayChassisExternalIDs(a map[string]string) map[string]string {
	if a == nil {
		return nil
	}
	b := make(map[string]string, len(a))
	for k, v := range a {
		b[k] = v
	}
	return b
}

func equalGatewayChassisExternalIDs(a, b map[string]string) bool {
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if w, ok := b[k]; !ok || v != w {
			return false
		}
	}
	return true
}

func (a *GatewayChassis) GetName() string {
	return a.Name
}

func (a *GatewayChassis) GetOptions() map[string]string {
	return a.Options
}

func copyGatewayChassisOptions(a map[string]string) map[string]string {
	if a == nil {
		return nil
	}
	b := make(map[string]string, len(a))
	for k, v := range a {
		b[k] = v
	}
	return b
}

func equalGatewayChassisOptions(a, b map[string]string) bool {
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if w, ok := b[k]; !ok || v != w {
			return false
		}
	}
	return true
}

func (a *GatewayChassis) GetPriority() int {
	return a.Priority
}

func (a *GatewayChassis) DeepCopyInto(b *GatewayChassis) {
	*b = *a
	b.ExternalIDs = copyGatewayChassisExternalIDs(a.ExternalIDs)
	b.Options = copyGatewayChassisOptions(a.Options)
}

func (a *GatewayChassis) DeepCopy() *GatewayChassis {
	b := new(GatewayChassis)
	a.DeepCopyInto(b)
	return b
}

func (a *GatewayChassis) CloneModelInto(b model.Model) {
	c := b.(*GatewayChassis)
	a.DeepCopyInto(c)
}

func (a *GatewayChassis) CloneModel() model.Model {
	return a.DeepCopy()
}

func (a *GatewayChassis) Equals(b *GatewayChassis) bool {
	return a.UUID == b.UUID &&
		a.ChassisName == b.ChassisName &&
		equalGatewayChassisExternalIDs(a.ExternalIDs, b.ExternalIDs) &&
		a.Name == b.Name &&
		equalGatewayChassisOptions(a.Options, b.Options) &&
		a.Priority == b.Priority
}

func (a *GatewayChassis) EqualsModel(b model.Model) bool {
	c := b.(*GatewayChassis)
	return a.Equals(c)
}

var _ model.CloneableModel = &GatewayChassis{}
var _ model.ComparableModel = &GatewayChassis{}
