// /*
// Copyright 2026 NVIDIA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//

//go:build linux

// Code generated by MockGen. DO NOT EDIT.
// Source: ipam.go
//
// Generated by this command:
//
//	mockgen -build_constraint linux -copyright_file ../../../../../hack/boilerplate.go.txt -destination mock/ipam.go -source ipam.go
//

// Package mock_ipam is a generated GoMock package.
package mock_ipam

import (
	reflect "reflect"

	types "github.com/containernetworking/cni/pkg/types"
	types100 "github.com/containernetworking/cni/pkg/types/100"
	gomock "go.uber.org/mock/gomock"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
	isgomock struct{}
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// ConfigureIface mocks base method.
func (m *MockAPI) ConfigureIface(ifName string, res *types100.Result) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureIface", ifName, res)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureIface indicates an expected call of ConfigureIface.
func (mr *MockAPIMockRecorder) ConfigureIface(ifName, res any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureIface", reflect.TypeOf((*MockAPI)(nil).ConfigureIface), ifName, res)
}

// ExecAdd mocks base method.
func (m *MockAPI) ExecAdd(plugin string, netconf []byte) (types.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecAdd", plugin, netconf)
	ret0, _ := ret[0].(types.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecAdd indicates an expected call of ExecAdd.
func (mr *MockAPIMockRecorder) ExecAdd(plugin, netconf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecAdd", reflect.TypeOf((*MockAPI)(nil).ExecAdd), plugin, netconf)
}

// ExecCheck mocks base method.
func (m *MockAPI) ExecCheck(plugin string, netconf []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecCheck", plugin, netconf)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecCheck indicates an expected call of ExecCheck.
func (mr *MockAPIMockRecorder) ExecCheck(plugin, netconf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecCheck", reflect.TypeOf((*MockAPI)(nil).ExecCheck), plugin, netconf)
}

// ExecDel mocks base method.
func (m *MockAPI) ExecDel(plugin string, netconf []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecDel", plugin, netconf)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecDel indicates an expected call of ExecDel.
func (mr *MockAPIMockRecorder) ExecDel(plugin, netconf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecDel", reflect.TypeOf((*MockAPI)(nil).ExecDel), plugin, netconf)
}
