// /*
// Copyright 2026 NVIDIA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nvidia/doca-platform/pkg/ecpf (interfaces: ECPFManager)
//
// Generated by this command:
//
//	mockgen -copyright_file ../../hack/boilerplate.go.txt -package mock -destination mock/manager.go . ECPFManager
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	v1alpha1 "github.com/nvidia/doca-platform/api/dpuservice/v1alpha1"
	gomock "go.uber.org/mock/gomock"
)

// MockECPFManager is a mock of ECPFManager interface.
type MockECPFManager struct {
	ctrl     *gomock.Controller
	recorder *MockECPFManagerMockRecorder
	isgomock struct{}
}

// MockECPFManagerMockRecorder is the mock recorder for MockECPFManager.
type MockECPFManagerMockRecorder struct {
	mock *MockECPFManager
}

// NewMockECPFManager creates a new mock instance.
func NewMockECPFManager(ctrl *gomock.Controller) *MockECPFManager {
	mock := &MockECPFManager{ctrl: ctrl}
	mock.recorder = &MockECPFManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockECPFManager) EXPECT() *MockECPFManagerMockRecorder {
	return m.recorder
}

// GetRepresentorForPFServiceInterface mocks base method.
func (m *MockECPFManager) GetRepresentorForPFServiceInterface(pfsi *v1alpha1.PF) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepresentorForPFServiceInterface", pfsi)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepresentorForPFServiceInterface indicates an expected call of GetRepresentorForPFServiceInterface.
func (mr *MockECPFManagerMockRecorder) GetRepresentorForPFServiceInterface(pfsi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepresentorForPFServiceInterface", reflect.TypeOf((*MockECPFManager)(nil).GetRepresentorForPFServiceInterface), pfsi)
}

// GetRepresentorForVFServiceInterface mocks base method.
func (m *MockECPFManager) GetRepresentorForVFServiceInterface(vfsi *v1alpha1.VF) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepresentorForVFServiceInterface", vfsi)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepresentorForVFServiceInterface indicates an expected call of GetRepresentorForVFServiceInterface.
func (mr *MockECPFManagerMockRecorder) GetRepresentorForVFServiceInterface(vfsi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepresentorForVFServiceInterface", reflect.TypeOf((*MockECPFManager)(nil).GetRepresentorForVFServiceInterface), vfsi)
}
