/*
Copyright 2026 NVIDIA

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by dpfdev generate-deprecation-warnings. DO NOT EDIT.

package deprecation

import "k8s.io/apimachinery/pkg/runtime/schema"

// KnownDeprecations lists every deprecated field found across the DPF CRDs at build time.
var KnownDeprecations = []GVKDeprecations{
	{
		GVK:      schema.GroupVersionKind{Group: "operator.dpu.nvidia.com", Version: "v1alpha1", Kind: "DPFOperatorConfig"},
		ListKind: "DPFOperatorConfigList",
		Fields: []DeprecatedField{
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "dpuDetector"}, {Name: "image"}},
				Description: "Image overrides the container image used by the DPUDetector Container.\n\nDeprecated: This field is deprecated and will be removed with v27.1.0.\nUse the new field `daemon` instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "dpuServiceController"}, {Name: "image"}},
				Description: "Image overrides the container image used by the DPUService controller.\n\nDeprecated: This field is deprecated and will be removed with v27.1.0.\nUse the new field `controller` instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "flannel"}, {Name: "image"}},
				Description: "Images overrides the container images used by flannel\n\nDeprecated: This field is deprecated and will be removed with v27.1.0.\nUse the new fields `cni` and `daemon` instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "kamajiClusterManager"}, {Name: "image"}},
				Description: "Image overrides the container image used by the Kamaji Cluster Manager.\n\nDeprecated: This field is deprecated and will be removed with v27.1.0.\nUse the new field `controller` instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "multus"}, {Name: "image"}},
				Description: "Image overrides the container image used by the Multus Container.\n\nDeprecated: This field is deprecated and will be removed with v27.1.0.\nUse the new field `cni` instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "nvipam"}, {Name: "image"}},
				Description: "Image overrides the container image used by the NVIPAM controller.\n\nDeprecated: This field is deprecated and will be removed with v27.1.0.\nUse the new field `controller` instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "ovsCNI"}},
				Description: "OVSCNI is the configuration for OVSCNI\n\nDeprecated: OVS CNI is installed by CNIInstaller. Remove in 27.1.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "provisioningController"}, {Name: "bfCFGTemplateConfigMap"}},
				Description: "BFCFGTemplateConfigMap is the name of a configMap containing a template for the BF.cfg file used by the DPU controller.\nBy default the provisioning controller use a hardcoded BF.cfg e.g. https://github.com/NVIDIA/doca-platform/blob/release-v24.10/internal/provisioning/controllers/dpu/bfcfg/bf.cfg.template\nNote: Replacing the bf.cfg is an advanced use case. The default bf.cfg is designed for most use cases.\n\nDeprecated: BFCFGTemplateConfigMap is deprecated and will be removed in a future release.\nUse enableDynamicBFCFGTemplates instead for custom bf.cfg templates.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "provisioningController"}, {Name: "image"}},
				Description: "Image overrides the container image used by the Provisioning controller.\n\nDeprecated: This field is deprecated and will be removed with v27.1.0.\nUse the new field `controller` instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "provisioningController"}, {Name: "installInterface"}, {Name: "installViaGNOI"}},
				Description: "InstallViaGNOI is the interface used to install the BFB via GNOI\n\nDeprecated: Use InstallViaHostAgent instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "provisioningController"}, {Name: "installInterface"}, {Name: "installViaRedfish"}, {Name: "bfbRegistry"}},
				Description: "BFBRegistry is the configuration for the BFB Registry\n\nDeprecated: Use RegistryConfiguration instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "provisioningController"}, {Name: "installInterface"}, {Name: "installViaRedfish"}, {Name: "bfbRegistryAddress"}},
				Description: "BFBRegistryAddress is the address of the BFB Registry\n\nDeprecated: Use RegistryConfiguration instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "provisioningController"}, {Name: "registry"}, {Name: "address"}},
				Description: "Address is the address used to access the BFB Registry. The address must start with \"http://\" or \"https://\".\nBy default, the BFB Registry can be accessed via its Service.\nFor non-kubernetes environments, this must be set due to the lack of kubelet on worker nodes.\nFor zero-trust environments, this must be set so that the BFB Registry can be accessed from DPU BMC.\nDeprecated: Address is deprecated and will be removed in a future release.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "provisioningController"}, {Name: "registry"}, {Name: "port"}},
				Description: "Port is the port on which the registry instances will listen\nDeprecated: Address is deprecated and will be removed in a future release.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "serviceSetController"}, {Name: "image"}},
				Description: "Image overrides the container image used by the ServiceChainSet Controller.\n\nDeprecated: This field is deprecated and will be removed with v27.1.0.\nUse the new field `controller` instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "sfcController"}, {Name: "image"}},
				Description: "Image overrides the container image used by the SFC controller.\n\nDeprecated: This field is deprecated and will be removed with v27.1.0.\nUse the new field `controller` instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "sriovDevicePlugin"}, {Name: "image"}},
				Description: "Image overrides the container image used by the SRIOV Device Plugin container.\n\nDeprecated: This field is deprecated and will be removed with v27.1.0.\nUse the new field `deviceplugin` instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "staticClusterManager"}, {Name: "image"}},
				Description: "Image overrides the container image used by the Static Cluster Manager.\n\nDeprecated: This field is deprecated and will be removed with v27.1.0.\nUse the new field `controller` instead.",
			},
		},
	},
	{
		GVK:      schema.GroupVersionKind{Group: "svc.dpu.nvidia.com", Version: "v1alpha1", Kind: "DPUDeployment"},
		ListKind: "DPUDeploymentList",
		Fields: []DeprecatedField{
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "dpus"}, {Name: "dpuSetStrategy"}, {Name: "rollingUpdate"}, {Name: "maxUnavailable"}},
				Description: "MaxUnavailable is the maximum number of DPUs that can be unavailable during the update.\n\nDeprecated: This field is deprecated and will be removed with v27.1.0.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "dpus"}, {Name: "dpuSets", IsArray: true}, {Name: "dpuSelector"}},
				Description: "DPUSelector defines the DPUs that the DPUSet should target\n\nDeprecated: This field is deprecated and will be removed with v27.1.0. Use DPUDeviceSelector instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "dpus"}, {Name: "dpuSets", IsArray: true}, {Name: "nodeSelector"}},
				Description: "NodeSelector defines the nodes that the DPUSet should target\n\nDeprecated: This field is deprecated and will be removed with v27.1.0. Use DPUNodeSelector instead.",
			},
		},
	},
	{
		GVK:      schema.GroupVersionKind{Group: "provisioning.dpu.nvidia.com", Version: "v1alpha1", Kind: "DPUDevice"},
		ListKind: "DPUDeviceList",
		Fields: []DeprecatedField{
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "opn"}},
				Description: "OPN is the Ordering Part Number of the device.\nIt's used to track the device's compatibility with different software versions.\nThis value is immutable and should not be changed once set.\nExample: \"900-9D3B4-00SV-EA0\"\n\nDeprecated: This field is deprecated and will be removed in a future version. Use status.opn instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "pf0Name"}},
				Description: "PF0Name is the name of the PF0 on the device.\nThis value is immutable and should not be changed once set.\nExample: \"eth0\"\n\nDeprecated: This field is deprecated and will be removed in a future version. Use status.pf0Name instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "psid"}},
				Description: "PSID is the Product Serial ID of the device.\nIt's used to track the device's lifecycle and for inventory management.\nThis value is immutable and should not be changed once set.\nExample: \"MT_0001234567\", \"MT25066004C7\"\n\nDeprecated: This field is deprecated and will be removed in a future version. Use status.psid instead.",
			},
		},
	},
	{
		GVK:      schema.GroupVersionKind{Group: "provisioning.dpu.nvidia.com", Version: "v1alpha1", Kind: "DPUNode"},
		ListKind: "DPUNodeList",
		Fields: []DeprecatedField{
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "nodeDMSAddress"}},
				Description: "The IP address and port where the DMS is exposed. Only applicable if dpuInstallInterface is set to gNOI.\n\nDeprecated: this field is no longer used.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "nodeRebootMethod"}, {Name: "gNOI"}},
				Description: "Use the DPU's DMS interface to reboot the host.\n\nDeprecated: Use HostAgent instead.",
			},
		},
	},
	{
		GVK:      schema.GroupVersionKind{Group: "provisioning.dpu.nvidia.com", Version: "v1alpha1", Kind: "DPU"},
		ListKind: "DPUList",
		Fields: []DeprecatedField{
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "bmcIP"}},
				Description: "BMCIP is the ip address of the DPU BMC\n\nDeprecated: Use BMCIP from DPUDevice instead.",
			},
		},
	},
	{
		GVK:      schema.GroupVersionKind{Group: "svc.dpu.nvidia.com", Version: "v1alpha1", Kind: "DPUServiceChain"},
		ListKind: "DPUServiceChainList",
		Fields: []DeprecatedField{
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "clusterSelector"}},
				Description: "Select the Clusters with specific labels, ServiceChainSet CRs will be created only for these Clusters\n\nDeprecated: This field is deprecated and will be removed with v27.1.0. Use DPUClusterSelector instead.",
			},
		},
	},
	{
		GVK:      schema.GroupVersionKind{Group: "svc.dpu.nvidia.com", Version: "v1alpha1", Kind: "DPUServiceInterface"},
		ListKind: "DPUServiceInterfaceList",
		Fields: []DeprecatedField{
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "clusterSelector"}},
				Description: "Select the Clusters with specific labels, ServiceInterfaceSet CRs will be created only for these Clusters\n\nDeprecated: This field is deprecated and will be removed with v27.1.0. Use DPUClusterSelector instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "template"}, {Name: "spec"}, {Name: "template"}, {Name: "spec"}, {Name: "ovn"}},
				Description: "The OVN definition\nDeprecated: This field is deprecated and will be removed with v26.10.0.\nMigrate to interfaceType=\"patch\" with spec.patch.peerBridge and spec.patch.peerPatchName instead.",
			},
		},
	},
	{
		GVK:      schema.GroupVersionKind{Group: "svc.dpu.nvidia.com", Version: "v1alpha1", Kind: "DPUServiceIPAM"},
		ListKind: "DPUServiceIPAMList",
		Fields: []DeprecatedField{
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "clusterSelector"}},
				Description: "ClusterSelector determines in which clusters the DPUServiceIPAM controller should apply the configuration.\n\nDeprecated: This field is deprecated and will be removed with v27.1.0. Use DPUClusterSelector instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "ipv4Network"}},
				Description: "IPV4Network is the configuration related to splitting a network into subnets per node, each with their own gateway.\n\nDeprecated: Use Network instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "ipv4Subnet"}},
				Description: "IPV4Subnet is the configuration related to splitting a subnet into blocks per node. In this setup, there is a\nsingle gateway.\n\nDeprecated: Use Subnet instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "network"}, {Name: "exclusions"}},
				Description: "Exclusions is a list of IPs that should be excluded when splitting the CIDR into subnets per node.\n\nDeprecated: This field is deprecated and will be removed with v26.10.0. Use ExcludeRanges instead.",
			},
		},
	},
	{
		GVK:      schema.GroupVersionKind{Group: "provisioning.dpu.nvidia.com", Version: "v1alpha1", Kind: "DPUSet"},
		ListKind: "DPUSetList",
		Fields: []DeprecatedField{
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "dpuSelector"}},
				Description: "Select the DPU with specific labels\n\nDeprecated: This field is deprecated and will be removed with v27.1.0. Use DPUDeviceSelector instead.",
			},
			{
				Segments:    []PathSegment{{Name: "spec"}, {Name: "strategy"}, {Name: "rollingUpdate"}, {Name: "maxUnavailable"}},
				Description: "MaxUnavailable is the maximum number of DPUs that can be unavailable during the update.\n\nDeprecated: This field is deprecated and will be removed with v27.1.0.",
			},
		},
	},
}
